src/objects/CMC_Estimate_Resource__c.object
<CustomObject>
    <fields>
        <fullName>E2_Estimate_Rate_Card__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to store the rate card reference of an estimate; This is a local reference to the estimate rate card record. Not used to display on the screen; Will be used only for reporting purpose.</description>
        <label>Estimate Rate Card</label>
        <referenceTo>E2_Estimate_Rate_Card__c</referenceTo>
        <relationshipLabel>Estimate Resources</relationshipLabel>
        <relationshipName>Estimate_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/CMC_Presales_LOE__c.object
<CustomObject>
</CustomObject>

src/objects/E2_Capacity__c.object
<CustomObject>
    <description>Estimator 2.0</description>
    <label>Capacity Needs</label>
    <nameField>
        <displayFormat>CAP-{0000}</displayFormat>
        <label>E2Capacity</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Capacity Needs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/E2_Estimate_Rate_Card__c.object
<CustomObject>
    <description>Object stores cloned copy of rate card for all resources with modified bill rate of related presales estimate.</description>
    <fields>
        <fullName>Estimate__c</fullName>
        <label>Estimate</label>
        <referenceTo>CMC_Presales_LOE__c</referenceTo>
        <relationshipLabel>Estimate Rate Cards</relationshipLabel>
        <relationshipName>Estimate_Rate_Cards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Estimate Rate Card</label>
    <nameField>
        <displayFormat>ERC-{0000}</displayFormat>
        <label>Estimate Rate Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Estimate Rate Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/E2_System_setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom setting object to store estimator 2.0 system settings</description>
    <fields>
        <fullName>Timeline_Discounts__c</fullName>
        <label>Timeline Discounts</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>E2 System Settings</label>
</CustomObject>

src/classes/E2_TimelineSummaryController.cls
/**=====================================================================
 * Appirio, Inc
 * Name: E2_TimelineSummaryController
 * Description: Controller class for E2_Timeline page
 * Created Date: Feb 28th, 2017
 * Created By: Rohit Sharma (Appirio)
 * 
 * Date Modified      Modified By         Description of the update
*  =====================================================================*/
public with sharing class E2_TimelineSummaryController {
    public Id estimateId{get;set;}
    public list<CMC_Presales_LOE__c> pricingMatrix;
    public map<Id,CMC_Presales_LOE__c> activeTimelineMap;
    public E2_System_setting__c e2SystemSetting{get;set;}
    public list<decimal> timelineDiscounts{get;set;}
    public map<id, map<string, decimal>> hourSummaryMap;
    public decimal totalHours{get;set;}
    public map<id, set<string>> timelineLevels{get;set;}
    public static final string TOTAL = 'Total';
    
    public E2_TimelineSummaryController() {
        timelineDiscounts = new list<decimal>();
        timelineLevels = new map<id, set<string>>();
        e2SystemSetting = E2_System_setting__c.getInstance();
        if(string.isNotBlank(e2SystemSetting.Timeline_Discounts__c)) {
            for(string discount : e2SystemSetting.Timeline_Discounts__c.split(E2_Constants.COMMA)) {
                timelineDiscounts.add(decimal.valueOf(discount));
            }
        }
        totalHours = 0;
    }
    
    public list<CMC_Presales_LOE__c> getPricingMatrix() {
            pricingMatrix = E2_DataUtil.getEstimateTimelinesSummary( estimateId );
        return pricingMatrix;
    }
    
    public map<Id, CMC_Presales_LOE__c> getActiveTimelineMap() {
            activeTimelineMap = new map<Id,CMC_Presales_LOE__c>();
            for(CMC_Presales_LOE__c timeline : getPricingMatrix()) {
                activeTimelineMap.put(timeline.id, timeline);
            }
        return activeTimelineMap;
    }
    
    public map<id, map<string, decimal>> getHourSummaryMap() {
            getActiveTimelineMap();
            hourSummaryMap = new  map<id, map<string, decimal>>();
            for(CMC_Estimate_Resource__c estimateResource : E2_DataUtil.getEstimateResourceForTimeline(activeTimelineMap.keySet())) {
                if(string.isNotBlank(estimateResource.E2_Estimate_Rate_Card__r.Resource_Level__c)) {
                    if(!hourSummaryMap.containsKey(estimateResource.Estimate__c)) {
                        hourSummaryMap.put(estimateResource.Estimate__c, new map<string, decimal>());
                    }
                    map<string, decimal> hoursMap = hourSummaryMap.get(estimateResource.Estimate__c);
                    if(!hoursMap.containsKey(estimateResource.E2_Estimate_Rate_Card__r.Resource_Level__c)) {
                            hoursMap.put(estimateResource.E2_Estimate_Rate_Card__r.Resource_Level__c, 0);
                    }
                    hoursMap.put(estimateResource.E2_Estimate_Rate_Card__r.Resource_Level__c, 
                                    hoursMap.get(estimateResource.E2_Estimate_Rate_Card__r.Resource_Level__c) + estimateResource.Total_Hours__c);
                    if(!hoursMap.containsKey(TOTAL)) hoursMap.put(TOTAL, 0);
                    hoursMap.put(TOTAL, hoursMap.get(TOTAL) + estimateResource.Total_Hours__c);

                }
            }
            set<string> resourcelevelTemp = new set<string>();
            for(Schema.PicklistEntry picklistValue : E2_Capacity__c.Level__c.getDescribe().getPicklistValues()){
                resourcelevelTemp.add(picklistValue.getLabel());
            }
            for(id timelineId : hourSummaryMap.keySet()) {
                timelineLevels.put(timelineId, new set<string>());
                for(string resourcelevel : resourcelevelTemp) {
                    map<string, decimal> hoursMap = hourSummaryMap.get(timelineId);
                    if(hoursMap.containsKey(resourcelevel))  timelineLevels.get(timelineId).add(resourcelevel);
                }
            }
        return hourSummaryMap;
    }
}