src/objects/CMC_Estimate_Resource__c.object
<CustomObject>
    <fields>
        <fullName>E2_Estimate_Rate_Card__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to store the rate card reference of an estimate; This is a local reference to the estimate rate card record. Not used to display on the screen; Will be used only for reporting purpose.</description>
        <label>Estimate Rate Card</label>
        <referenceTo>E2_Estimate_Rate_Card__c</referenceTo>
        <relationshipLabel>Estimate Resources</relationshipLabel>
        <relationshipName>Estimate_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/CMC_Estimate_Resource_Week__c.object
<CustomObject>
    <label>Estimate Resource Week</label>
    <nameField>
        <displayFormat>ERW-{00000}</displayFormat>
        <label>CMC Estimate Resource Week Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Estimate Resource Weeks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CMC_Estimate_Week__c.object
<CustomObject>
    <label>Estimate Week</label>
    <nameField>
        <label>Week Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimate Weeks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CMC_Presales_LOE__c.object
<CustomObject>
</CustomObject>

src/objects/E2_Estimate_Rate_Card__c.object
<CustomObject>
    <description>Object stores cloned copy of rate card for all resources with modified bill rate of related presales estimate.</description>
    <label>Estimate Rate Card</label>
    <nameField>
        <displayFormat>ERC-{0000}</displayFormat>
        <label>Estimate Rate Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Estimate Rate Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/E2_TimelineDataUtil_WSTest.cls
@isTest(seeAllData=false)
public class E2_TimelineDataUtil_WSTest {
  public static CMC_Presales_LOE__c estimate;
  public static pse__Rate_Card__c rateCard;
  public static E2_Estimate_Rate_Card__c estimateRC;
  public static CMC_Estimate_Resource__c resource;
  public static CMC_Estimate_Week__c week;
  public static CMC_Estimate_Resource_Week__c resWeek;
  
  public static testmethod void testDataUtil(){
    estimate = [SELECT Id, Discount_Percent__c FROM CMC_Presales_LOE__c];
    rateCard = [SELECT Id FROM pse__Rate_Card__c];
    estimateRC = [SELECT Id FROM E2_Estimate_Rate_Card__c];
    resource = [SELECT Id FROM CMC_Estimate_Resource__c];
    week = [SELECT Id FROM CMC_Estimate_Week__c];
    resWeek = [SELECT Id FROM CMC_Estimate_Resource_Week__c];
    User sysAdmin = E2_Test_Utils.insertSysAdminUser(true);    
    System.runAs(sysAdmin){
      //start test
      Test.startTest();
        system.assertEquals(E2_TimelineDataUtil_WS.getEstimateRateCards(estimate.Id).size(),1);
        system.assertEquals(E2_TimelineDataUtil_WS.getHoursforEstimateResourceWeek(week.Id, resource.Id).size(),1);
        Set<String> weekIds = new Set<String>();
        weekIds.add(week.Id);
        Set<String> resourceIds = new Set<String>();
        resourceIds.add(resource.Id);
        system.assertEquals(E2_TimelineDataUtil_WS.getEstimateResourceWeekRecords(weekIds, resourceIds).size(), 1);
        system.assertEquals(E2_TimelineDataUtil_WS.getCurrencyISOCodeonEstimate(estimate.Id).size(), 1);
        system.assertEquals(E2_TimelineDataUtil_WS.getEstimateWeekRecords(estimate.Id).size(), 1);
        system.assertEquals(E2_TimelineDataUtil_WS.getEstimateResourceAndResourceWeekRec(estimate.Id).size(), 1);
        system.assertEquals(E2_TimelineDataUtil_WS.getEstimateResourceForSkill(estimate.Id, resource.Id).size(), 1);
      //stop test
      Test.stopTest();
    }
  
  }
  
   //create test data
  @testSetup 
  public static void createTestData(){
    Account acc = E2_Test_Utils.insertAccount(true);
    Opportunity opp = E2_Test_Utils.insertOpportunity(acc.Id, true);
    Presales_Request__c psr = E2_Test_Utils.insertPresalesReq(opp.Id, 'Demo', false);
    insert psr;
    
    estimate = E2_Test_Utils.insertEstimate(psr.id, false);  
    insert estimate;
    
    pse__Region__c region = E2_Test_Utils.insertRegion(true);
    pse__Practice__c practice = E2_Test_Utils.insertPractice(true);
    
    rateCard = E2_Test_Utils.insertRateCard(acc.Id, region.Id, practice.Id, true);
    estimateRC = E2_Test_Utils.insertEstimateRateCard(estimate.Id, true);
    
    resource = E2_Test_Utils.insertCMCEstimateRes(estimate.Id, true);
    week = E2_Test_Utils.insertEstimateWeek(estimate.Id, true);
    resWeek = E2_Test_Utils.insertCMCEstimateResWeek(resource.Id, week.Id, true);
  }




}