src/objects/CMC_Presales_LOE__c.object
<CustomObject>
</CustomObject>

src/objects/E2_Scope__c.object
<CustomObject>
    <description>Estimator 2.0</description>
    <fields>
        <fullName>Complexity__c</fullName>
        <description>Complexity (High, Medium, Low)</description>
        <globalPicklist>E2_Complexity</globalPicklist>
        <inlineHelpText>Complexity of this scope(High, Medium, Low)</inlineHelpText>
        <label>Complexity</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of this scope</description>
        <inlineHelpText>Description of this scope</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>E2_Assumption__c</fullName>
        <label>Assumption</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>LOE_Hrs__c</fullName>
        <description>Calculated base field for estimates depending on complexity selected.</description>
        <inlineHelpText>Calculated base field for estimates depending on complexity selected.</inlineHelpText>
        <label>LOE Hrs</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Scope__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent scope of this scope.</description>
        <inlineHelpText>(Optional) - Parent scope of this scope.</inlineHelpText>
        <label>Parent Scope</label>
        <referenceTo>E2_Scope__c</referenceTo>
        <relationshipName>Child_Scopes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scope_Item_Type__c</fullName>
        <inlineHelpText>Optional Field that you can use to specify if a scope item should be considered as an Epic, Story or Component.  This will allow you to filter when exporting to CMC.</inlineHelpText>
        <label>Scope Item Type</label>
        <picklist>
            <picklistValues>
                <fullName>Component</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Epic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Story</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capability</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Scope</label>
    <nameField>
        <label>Scope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scope</pluralLabel>
    <recordTypes>
        <fullName>Scope</fullName>
        <active>true</active>
        <description>Default Scope Record type. Mostly all scope should use this record type</description>
        <label>Scope</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/E2_ExportScopeItemsToCSVController.cls
public with sharing class E2_ExportScopeItemsToCSVController {
  public string header{get;set;}
  public string headerXLS{get;set;}
  public List<ScopeWrapper> lstScopeWrapper {get; set;}
  public CMC_Presales_LOE__c estimate {get;set;}
  
  public E2_ExportScopeItemsToCSVController(ApexPages.StandardController std){
  	this.estimate = (CMC_Presales_LOE__c)std.getRecord();
  	lstScopeWrapper = new List<ScopeWrapper>();
  	header = E2_Constants.SCOPE_CSV_HEADER;
  	headerXLS = E2_Constants.SCOPE_XLS_HEADER;
  }
  
  public void pageAction(){
  	List<E2_Scope__c> lstScopeItems = E2_DataUtil.getActiveChildScopesOfEstimate(String.valueOf(estimate.Id));
    for(E2_Scope__c scope : lstScopeItems){
    	ScopeWrapper wrapper = new ScopeWrapper();
    	wrapper.parentScope = scope.Parent_Scope__c == null ? '' : scope.Parent_Scope__r.name;
    	wrapper.scopeName = scope.Name;
    	wrapper.complexity = scope.Complexity__c;
    	wrapper.scopeItemtype = scope.Scope_Item_Type__c;    	
    	wrapper.description = scope.Description__c;
    	wrapper.assumption = scope.E2_Assumption__c;
    	wrapper.loeHrs = (scope.LOE_Hrs__c != null) ? String.valueOf(scope.LOE_Hrs__c) : '0';    	 	
    	lstScopeWrapper.add(wrapper);
    }
  }  
  
  public class ScopeWrapper{
  	public string parentScope {get; set;}
  	public string scopeName {get; set;}
    public string complexity{get; set;}
    public string scopeItemtype{get; set;}    
    public string description{get; set;}
    public string assumption{get; set;}
    public string loeHrs{get; set;}    
  }
}