src/objects/CMC_Presales_LOE__c.object
<CustomObject>
</CustomObject>

src/objects/E2_Scope__c.object
<CustomObject>
    <description>Estimator 2.0</description>
    <fields>
        <fullName>Complexity__c</fullName>
        <description>Complexity (High, Medium, Low)</description>
        <globalPicklist>E2_Complexity</globalPicklist>
        <inlineHelpText>Complexity of this scope(High, Medium, Low)</inlineHelpText>
        <label>Complexity</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Presales_LOE__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Relationship to Presales LOE</description>
        <inlineHelpText>Associated Estimate Record</inlineHelpText>
        <label>Estimate</label>
        <referenceTo>CMC_Presales_LOE__c</referenceTo>
        <relationshipName>E2_Scopes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Scope</label>
    <nameField>
        <label>Scope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scope</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/E2_ExportScopeItemsToCSVControllerTest.cls
@isTest
private class E2_ExportScopeItemsToCSVControllerTest {
	public static CMC_Presales_LOE__c estimate;
  
  static testMethod void testExportScopeList() {
  	Profile p = [SELECT Id FROM Profile WHERE Name =: E2_Constants.PROFILE_SYS_ADMIN ];
    User sysAdmin = new User();
    sysAdmin.Id = UserInfo.getUserId(); 
    sysAdmin.profileid = p.Id;
    update sysAdmin;
    
    estimate = [SELECT Id FROM CMC_Presales_LOE__c];
    
    System.runAs(sysAdmin){
    	Test.startTest();    
        PageReference pageRef = Page.E2_ExportScopeItemsToCSV;
        ApexPages.StandardController stdController = new ApexPages.StandardController(estimate);
        E2_ExportScopeItemsToCSVController controller = new E2_ExportScopeItemsToCSVController(stdController);
        controller.pageAction();
        system.assertEquals(1, controller.lstScopeWrapper.size());
      Test.stopTest();
    } 
  }
  
  @testSetup
  private static void createTestData(){
  	Account acc = E2_Test_Utils.insertAccount(true);
    Opportunity opp = E2_Test_Utils.insertOpportunity(acc.Id, true);        
    Presales_Request__c psr = E2_Test_Utils.insertPresalesReq(opp.Id, 'Demo', true);
    estimate = E2_Test_Utils.insertEstimate(psr.Id, true);
    
    E2_Scope__c childSC = E2_Test_Utils.insertScope(false);
    childSC.Presales_LOE__c = estimate.Id;
    childSC.Complexity__c = 'Medium';
    insert childSC;
  }
     
}