src/objects/CMC_Estimate_Resource__c.object
<CustomObject>
    <fields>
        <fullName>E2_Estimate_Rate_Card__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to store the rate card reference of an estimate; This is a local reference to the estimate rate card record. Not used to display on the screen; Will be used only for reporting purpose.</description>
        <label>Estimate Rate Card</label>
        <referenceTo>E2_Estimate_Rate_Card__c</referenceTo>
        <relationshipLabel>Estimate Resources</relationshipLabel>
        <relationshipName>Estimate_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/CMC_Estimate_Resource_Week__c.object
<CustomObject>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Estimate Resource Week</label>
    <nameField>
        <displayFormat>ERW-{00000}</displayFormat>
        <label>CMC Estimate Resource Week Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Estimate Resource Weeks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CMC_Estimate_Week__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Estimate__c</fullName>
        <label>Estimate</label>
        <referenceTo>CMC_Presales_LOE__c</referenceTo>
        <relationshipLabel>Estimate Weeks</relationshipLabel>
        <relationshipName>Estimate_Weeks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <description>The order the weeks are displayed in the Estimator</description>
        <inlineHelpText>The order the weeks are displayed in the Estimator</inlineHelpText>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <description>Phase this week resides in</description>
        <inlineHelpText>Phase this week resides in</inlineHelpText>
        <label>Phase</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Estimate Week</label>
    <nameField>
        <label>Week Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimate Weeks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CMC_Presales_LOE__c.object
<CustomObject>
</CustomObject>

src/objects/E2_Capacity__c.object
<CustomObject>
    <description>Estimator 2.0</description>
    <fields>
        <fullName>Estimator__c</fullName>
        <description>The Estimate on which the capacity is created based on specified and derived efforts.</description>
        <inlineHelpText>The Estimate on which the capacity is created based on specified and derived efforts.</inlineHelpText>
        <label>Estimate</label>
        <referenceTo>CMC_Presales_LOE__c</referenceTo>
        <relationshipName>E2_Capacity</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The number of hours assigned for a particular role on a particular phase.</description>
        <inlineHelpText>The number of hours assigned for a particular role on a particular phase.</inlineHelpText>
        <label>Hours</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <globalPicklist>E2_Phases</globalPicklist>
        <label>Phase</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <description>The Role on which the hours on a particular phase are assigned in the capacity.</description>
        <globalPicklist>E2_Role</globalPicklist>
        <inlineHelpText>The Role on which the hours on a particular phase are assigned in the capacity.</inlineHelpText>
        <label>Role</label>
        <type>Picklist</type>
    </fields>
    <label>Capacity Needs</label>
    <nameField>
        <displayFormat>CAP-{0000}</displayFormat>
        <label>E2Capacity</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Capacity Needs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/E2_Effort__c.object
<CustomObject>
    <description>Estimator 2.0</description>
    <fields>
        <fullName>Phase__c</fullName>
        <description>In what Phase....</description>
        <globalPicklist>E2_Phases</globalPicklist>
        <inlineHelpText>During which Phase is this effort expended?</inlineHelpText>
        <label>Phase</label>
        <type>Picklist</type>
    </fields>
    <label>Effort</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Efforts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/E2_Estimate_Milestone__c.object
<CustomObject>
    <description>This object is used to store all the milestone details associated with a presales estimate. Related to Estimator 2.0 App</description>
    <fields>
        <fullName>Estimate__c</fullName>
        <description>Association with presales estimate</description>
        <label>Estimate</label>
        <referenceTo>CMC_Presales_LOE__c</referenceTo>
        <relationshipLabel>Estimate Milestones</relationshipLabel>
        <relationshipName>Estimate_Milestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <description>Order</description>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Estimate Milestone</label>
    <nameField>
        <displayFormat>EM-{0000000000}</displayFormat>
        <label>Estimate Milestone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Estimate Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/E2_Estimate_Milestone_Week__c.object
<CustomObject>
    <description>Junction object between Estimate Milestone and Estimate Week. Used in Estimator 2.0 App</description>
    <fields>
        <fullName>Estimate_Milestone__c</fullName>
        <label>Estimate Milestone</label>
        <referenceTo>E2_Estimate_Milestone__c</referenceTo>
        <relationshipLabel>Estimate Milestone Weeks</relationshipLabel>
        <relationshipName>Estimate_Milestone_Weeks</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TextColorCode__c</fullName>
        <description>Stores the hex color code for the milestone descriptions</description>
        <label>TextColorCode</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Estimate Milestone Week</label>
    <nameField>
        <displayFormat>EMW-{0000000000}</displayFormat>
        <label>Estimate Milestone Week Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Estimate Milestone Weeks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/E2_Estimate_Rate_Card__c.object
<CustomObject>
    <description>Object stores cloned copy of rate card for all resources with modified bill rate of related presales estimate.</description>
    <fields>
        <fullName>Estimate__c</fullName>
        <label>Estimate</label>
        <referenceTo>CMC_Presales_LOE__c</referenceTo>
        <relationshipLabel>Estimate Rate Cards</relationshipLabel>
        <relationshipName>Estimate_Rate_Cards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Estimate Rate Card</label>
    <nameField>
        <displayFormat>ERC-{0000}</displayFormat>
        <label>Estimate Rate Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Estimate Rate Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/E2_Estimate_Week_Milestone__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Estimate__c</fullName>
        <label>Estimate</label>
        <referenceTo>CMC_Presales_LOE__c</referenceTo>
        <relationshipLabel>Estimate Week Milestones</relationshipLabel>
        <relationshipName>Estimate_Week_Milestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Estimate Week Milestone</label>
    <nameField>
        <label>Week Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimate Week Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/E2_Scope__c.object
<CustomObject>
    <description>Estimator 2.0</description>
    <fields>
        <fullName>Parent_Scope__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent scope of this scope.</description>
        <inlineHelpText>(Optional) - Parent scope of this scope.</inlineHelpText>
        <label>Parent Scope</label>
        <referenceTo>E2_Scope__c</referenceTo>
        <relationshipName>Child_Scopes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Presales_LOE__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Relationship to Presales LOE</description>
        <inlineHelpText>Associated Estimate Record</inlineHelpText>
        <label>Estimate</label>
        <referenceTo>CMC_Presales_LOE__c</referenceTo>
        <relationshipName>E2_Scopes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ultimate_Parent_Scope__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the ultimate (topmost )scope that the current scope is pointing to.</description>
        <inlineHelpText>This is the ultimate i.e. the topmost scope that the current scope is pointing to.</inlineHelpText>
        <label>Ultimate Parent Scope</label>
        <referenceTo>E2_Scope__c</referenceTo>
        <relationshipName>E2_Scopes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Scope</label>
    <nameField>
        <label>Scope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scope</pluralLabel>
    <recordTypes>
        <fullName>Scope</fullName>
        <active>true</active>
        <description>Default Scope Record type. Mostly all scope should use this record type</description>
        <label>Scope</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/E2_Clone_DataUtil_WSTest.cls
/**=====================================================================
 * Appirio, Inc
 * Name: E2_Clone_DataUtil_WSTest
 * Description: Class include all test methods uses to perform unit test over E2_Clone_DataUtil_WS class.
 * Created Date: Nov 23rd, 2016
 * Created By: Jitendra Jangid (Appirio)
 * 
 * Date Modified      Modified By                  Description of the update
 * Nov 23, 2016       Jitendra Jangid              S-454105 : Utility class as Data Tier for E2_Clone_Estimate_WS (webservice)
 * Feb 27, 2017       Jitendra Jangid              S-404442: Create multiple timelines on an estimate.[Updated few mathods calling since method signature got changed.]
*  =====================================================================*/

@isTest
private class E2_Clone_DataUtil_WSTest {
    
private static CMC_Presales_LOE__c estimate;
private static User sysAdmin;

@isTest
public static void testGetEstimateFullDetailById(){
    sysAdmin=getSysAdminUser();
    
    system.runAs(sysAdmin){
        Test.startTest();
        estimate=[Select ID from CMC_Presales_LOE__c];
        
        List<CMC_Presales_LOE__c> lsEstimate= E2_Clone_DataUtil_WS.getEstimateFullDetailById(estimate.ID);
        System.assert(lsEstimate.size()==1, 'Unit test failed: unable to retrieve estimate details with '+estimate.ID +' estimate_id.');
        
        Test.stopTest();
    }
    
}

@isTest
public static void testGetFullScopesDetailsByEstimateId(){
    sysAdmin=getSysAdminUser();
    
    system.runAs(sysAdmin){
        Test.startTest();
        estimate=[Select ID from CMC_Presales_LOE__c];
        List<E2_scope__c> lsScope= E2_Clone_DataUtil_WS.getFullScopesDetailsByEstimateId(estimate.ID);
        System.assert(lsScope.size()==2, 'Unit test failed: unable to retrieve all scope associated with '+estimate.ID +' estimate_id.');
        
        Test.stopTest();
    }
}

@isTest
public static void testGetCapacityListByEstimateId(){
    sysAdmin=getSysAdminUser();
    
    system.runAs(sysAdmin){
        Test.startTest();
        estimate=[Select ID from CMC_Presales_LOE__c];
        List<E2_Capacity__c> lsCapacity= E2_Clone_DataUtil_WS.getCapacityListByEstimateId(estimate.ID);
        System.assert(lsCapacity.size()==2, 'Unit test failed: unable to retrieve all capacity associated with '+estimate.ID +' estimate_id.');
        
        Test.stopTest();
    }
}

@isTest
public static void testGetEstimateWeekMilestonesByEstimateId(){
    
    sysAdmin=getSysAdminUser();
    
    system.runAs(sysAdmin){
        Test.startTest();
        estimate=[Select ID from CMC_Presales_LOE__c];
        list<E2_Estimate_Week_Milestone__c> lsWeekMilestone= E2_Clone_DataUtil_WS.getEstimateWeekMilestonesByEstimateId(estimate.ID);
        System.assert(lsWeekMilestone.size()==1, 'Unit test failed: unable to retrieve all milestone week associated with '+estimate.ID +' estimate_id.');
        
        Test.stopTest();
    }
}

@isTest
public static void testGetEstimateMilestonesByEstimateId(){
    
    
    sysAdmin=getSysAdminUser();
    
    system.runAs(sysAdmin){
        Test.startTest();
        estimate=[Select ID from CMC_Presales_LOE__c];
        list<E2_Estimate_Milestone__c> lsEstimateMilestone= E2_Clone_DataUtil_WS.getEstimateMilestonesByEstimateId(estimate.ID);
        System.assert(lsEstimateMilestone.size()==1, 'Unit test failed: unable to retrieve all milestones associated with '+estimate.ID +' estimate_id.');
        
        Test.stopTest();
    }
}

@isTest
public static void testGetMilestonesWeeks(){
    
    sysAdmin=getSysAdminUser();
    
    system.runAs(sysAdmin){
        Test.startTest();
        E2_Estimate_Milestone__c milestone=[Select ID from E2_Estimate_Milestone__c];
        Set<String> setMilestoneID=new Set<String>();
        setMilestoneID.add(milestone.ID);
        
        E2_Estimate_Week_Milestone__c weekMilestone=[Select ID from E2_Estimate_Week_Milestone__c];
        Set<String> setWeekID=new Set<String>();
        setWeekID.add(weekMilestone.ID);
        list<E2_Estimate_Milestone_Week__c> lsMileStoneWeek= E2_Clone_DataUtil_WS.getMilestonesWeeks(setMilestoneID,setWeekID);
        System.assert(lsMileStoneWeek.size()==1, 'Unit test failed: unable to retrieve all milestone week associated with estimate_id.');
        
        Test.stopTest();
    }
}

@isTest
public static void testGetEstimateRateCardsByEstimateId(){
    
    sysAdmin=getSysAdminUser();
    
    system.runAs(sysAdmin){
        Test.startTest();
        Set<String> setEstimateID=getEstimateIDSet();
        
        list<E2_Estimate_Rate_Card__c> lsRateCard= E2_Clone_DataUtil_WS.getEstimateRateCardsByEstimateId(setEstimateID);
        System.assert(lsRateCard.size()==1, 'Unit test failed: unable to retrieve all rate cards associated with estimate.');
        
        Test.stopTest();
    }
}

@isTest
public static void testGetEstimateWeekMByEstimateId(){
    
    sysAdmin=getSysAdminUser();
    
    system.runAs(sysAdmin){
        Test.startTest();
        Set<String> setEstimateID=getEstimateIDSet();
        list<CMC_Estimate_Week__c> lsTimelineWeek= E2_Clone_DataUtil_WS.getEstimateWeekMByEstimateId(setEstimateID);
        System.assert(lsTimelineWeek.size()==1, 'Unit test failed: unable to retrieve all timeline week associated with estimate.');
        
        Test.stopTest();
    }
}

@isTest
public static void testGetResourceRequestByEstimateId(){
    
    sysAdmin=getSysAdminUser();
    
    system.runAs(sysAdmin){
        Test.startTest();
        Set<String> setEstimateID=getEstimateIDSet();
        list<CMC_Estimate_Resource__c> lsEstimateResource = E2_Clone_DataUtil_WS.getResourceRequestByEstimateId(setEstimateID);
        System.assert(lsEstimateResource.size()==1, 'Unit test failed: unable to retrieve all resources associated with estimate.');
        
        Test.stopTest();
    }
}

@isTest
public static void testGetResourceWeeks(){
    
    
    sysAdmin=getSysAdminUser();
    
    system.runAs(sysAdmin){
        Test.startTest();
        CMC_Estimate_Resource__c resource=[Select ID from CMC_Estimate_Resource__c];
        Set<String> setResourceID=new Set<String>();
        setResourceID.add(resource.ID);
        
        CMC_Estimate_Week__c week=[Select ID from CMC_Estimate_Week__c];
        Set<String> setWeekID=new Set<String>();
        setWeekID.add(week.ID);
        list<CMC_Estimate_Resource_Week__c> lsTimelineWeek = E2_Clone_DataUtil_WS.getResourceWeeks(setResourceID,setWeekID);
        System.assert(lsTimelineWeek.size()==1, 'Unit test failed: unable to retrieve all timeline weeks associated based on resources and weeks');
        
        Test.stopTest();
    }
}

private static Set<String> getEstimateIDSet(){
    Set<String> setEstimateID=new Set<String>();
    for(CMC_Presales_LOE__c est:[Select ID from CMC_Presales_LOE__c]){
       setEstimateID.add(est.ID);
    }
    
    return setEstimateID;
}
private static User getSysAdminUser(){
    sysAdmin=E2_Test_Utils.insertUser(E2_Constants.PROFILE_SYS_ADMIN,true);
    return sysAdmin;
} 

@testSetup
private static void createTestData(){
    
    // sysAdmin=E2_Test_Utils.insertUser(E2_Constants.PROFILE_SYS_ADMIN,true);
    Account acc = E2_Test_Utils.insertAccount(true);
    Opportunity opp = E2_Test_Utils.insertOpportunity(acc.Id, true);        
    Presales_Request__c psr = E2_Test_Utils.insertPresalesReq(opp.Id, 'Demo', true);
    estimate = E2_Test_Utils.insertEstimate(psr.Id, true);
    
    //Create Scopes and associate them with estimate.
    E2_Scope__c parentScope=E2_Test_Utils.insertScope(false);
    parentScope.Presales_LOE__c=estimate.ID;
    insert parentScope;
    
    E2_Scope__c childScope=E2_Test_Utils.insertScope(false);
    childScope.Presales_LOE__c=estimate.ID;
    childScope.Parent_Scope__c=parentScope.ID;
    childScope.Ultimate_Parent_Scope__c=parentScope.ID;
    insert childScope;
    
    //insert effort and associate it with child scope
    E2_Effort__c childEffort=E2_Test_Utils.insertEffort(true,childScope.ID);
    
    //insert capacity and associate them with estimate
    E2_Capacity__c capacity=new E2_Capacity__c();
    capacity.Estimator__c=estimate.ID;
    capacity.Role__c='Developer';
    capacity.Phase__c='Build';
    capacity.Hours__c=40;
    insert capacity;
    
    capacity=new E2_Capacity__c();
    capacity.Estimator__c=estimate.ID;
    capacity.Role__c='QA Tester';
    capacity.Phase__c='Test';
    capacity.Hours__c=40;
    insert capacity;
    
    
    //insert weeks over milestone and associate them with estimate
    E2_Estimate_Week_Milestone__c weekMilestones = new E2_Estimate_Week_Milestone__c(Name = 'Week1',Estimate__c = estimate.Id, Order__c = 1,Date__c = system.today());
    insert weekMilestones;
    E2_Estimate_Milestone__c milestone = E2_Test_Utils.insertEstimateMilestone(estimate.Id, true);
    E2_Estimate_Milestone_Week__c milestoneWk = new E2_Estimate_Milestone_Week__c(Estimate_Milestone__c = milestone.Id, Estimate_Week_Milestone__c = weekMilestones.Id,TextColorCode__c = 'Red'); 
    insert milestoneWk;
    
    //Insert Ratecard
    E2_Estimate_Rate_Card__c estimateRC = E2_Test_Utils.insertEstimateRateCard(estimate.Id, true);
    
    
    CMC_Estimate_Resource__c resource = E2_Test_Utils.insertCMCEstimateRes(estimate.Id, true);
    CMC_Estimate_Week__c week = E2_Test_Utils.insertEstimateWeek(estimate.Id, true);
    CMC_Estimate_Resource_Week__c resWeek = E2_Test_Utils.insertCMCEstimateResWeek(resource.Id, week.Id, true);
    
    
    
}
	
	

}