src/objects/CMC_Estimate_Resource__c.object
<CustomObject>
    <fields>
        <fullName>E2_Estimate_Rate_Card__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to store the rate card reference of an estimate; This is a local reference to the estimate rate card record. Not used to display on the screen; Will be used only for reporting purpose.</description>
        <label>Estimate Rate Card</label>
        <referenceTo>E2_Estimate_Rate_Card__c</referenceTo>
        <relationshipLabel>Estimate Resources</relationshipLabel>
        <relationshipName>Estimate_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>E2_Role__c</fullName>
        <description>This is an additional field to store role in E2 format.</description>
        <inlineHelpText>This is an additional field to store role in E2 format.</inlineHelpText>
        <label>E2 Role</label>
        <length>200</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/CMC_Estimate_Resource_Week__c.object
<CustomObject>
    <fields>
        <fullName>Estimate_Resource__c</fullName>
        <label>Estimate Resource</label>
        <referenceTo>CMC_Estimate_Resource__c</referenceTo>
        <relationshipName>Estimate_Resource_Weeks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Estimate_Week__c</fullName>
        <label>Estimate Week</label>
        <referenceTo>CMC_Estimate_Week__c</referenceTo>
        <relationshipName>Estimate_Resource_Weeks</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Estimate Resource Week</label>
    <nameField>
        <displayFormat>ERW-{00000}</displayFormat>
        <label>CMC Estimate Resource Week Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Estimate Resource Weeks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CMC_Estimate_Week__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>E2_Milestone1ColorCode__c</fullName>
        <description>This field is used for sub-milestones color code</description>
        <label>Milestone1ColorCode</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>E2_Milestone1__c</fullName>
        <description>This field is used for sub-milestones</description>
        <inlineHelpText>This field is used for sub-milestones</inlineHelpText>
        <label>Milestone1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>E2_Milestone2ColorCode__c</fullName>
        <description>This field is used for sub-milestones color code</description>
        <label>Milestone2ColorCode</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>E2_Milestone2__c</fullName>
        <description>This field is used for sub-milestones</description>
        <label>Milestone2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>E2_MilestoneColorCode__c</fullName>
        <description>This field contains the Hex HTML color code value; Used in Estimator 2.0 APP</description>
        <inlineHelpText>Need Hex Code RGB (eg. #FFFFFF)</inlineHelpText>
        <label>MilestoneColorCode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>E2_PhaseColorCode__c</fullName>
        <description>This field contains the hex code value of html color codes; used in Estimator 2.0 App</description>
        <inlineHelpText>Need Hex Code RGB (eg. #FFFFFF)</inlineHelpText>
        <label>PhaseColorCode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Estimate__c</fullName>
        <label>Estimate</label>
        <referenceTo>CMC_Presales_LOE__c</referenceTo>
        <relationshipLabel>Estimate Weeks</relationshipLabel>
        <relationshipName>Estimate_Weeks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <label>Milestone</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <description>The order the weeks are displayed in the Estimator</description>
        <inlineHelpText>The order the weeks are displayed in the Estimator</inlineHelpText>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <description>Phase this week resides in</description>
        <inlineHelpText>Phase this week resides in</inlineHelpText>
        <label>Phase</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Estimate Week</label>
    <nameField>
        <label>Week Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimate Weeks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CMC_Presales_LOE__c.object
<CustomObject>
</CustomObject>

src/objects/E2_Estimate_Rate_Card__c.object
<CustomObject>
    <description>Object stores cloned copy of rate card for all resources with modified bill rate of related presales estimate.</description>
    <fields>
        <fullName>Bill_Rate__c</fullName>
        <label>Bill Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Discounted_Rate__c</fullName>
        <label>Discounted Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Estimate__c</fullName>
        <label>Estimate</label>
        <referenceTo>CMC_Presales_LOE__c</referenceTo>
        <relationshipLabel>Estimate Rate Cards</relationshipLabel>
        <relationshipName>Estimate_Rate_Cards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Practice__c</fullName>
        <label>Practice</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate_Card__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rate Card</label>
        <referenceTo>pse__Rate_Card__c</referenceTo>
        <relationshipLabel>Estimate Rate Cards</relationshipLabel>
        <relationshipName>Estimate_Rate_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Resource region from rate card region lookup</description>
        <label>Region</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Resource_Cost__c</fullName>
        <label>Resource Cost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Resource_Role__c</fullName>
        <label>Resource Role</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Estimate Rate Card</label>
    <nameField>
        <displayFormat>ERC-{0000}</displayFormat>
        <label>Estimate Rate Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Estimate Rate Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/E2_TimelineDataUtil_WS.cls
/**=====================================================================
 * Appirio, Inc
 * Name: E2_TimelineDataUtil_WS
 * Description: This is the utility class used by E2_TimelineWSManager.cls
 * Created Date: Aug 26, 2016
 * Created By: Arpita Bose(Appirio)
 * 08 Sep 2016: Modified: RJ : Added E2_Estimate_Rate_Card__r.Resource_Role__c, E2_Estimate_Rate_Card__r.Region__c field in the query in getEstimateResourceAndResourceWeekRec method for 
 *                             Capacity Needs and Timeline Hours based on roles
*  =====================================================================*/
public class E2_TimelineDataUtil_WS {
  //method to get E2_Estimate_Rate_Card__c records for an estimateId
  public static List<E2_Estimate_Rate_Card__c> getEstimateRateCards(String estimateId){
    return [SELECT Id, Resource_Role__c, Estimate__c, Region__c, 
              Practice__c, Code__c, Rate_Card__c, Resource_Cost__c,
              Bill_Rate__c, Discounted_Rate__c, Category__c  
              FROM E2_Estimate_Rate_Card__c 
              WHERE Estimate__c = :estimateId
              ORDER BY Region__c ASC, Resource_Role__c ASC];
  }
  
  //method to get Hours from CMC_Estimate_Resource_Week__c for a week and a resource
  public static List<CMC_Estimate_Resource_Week__c> getHoursforEstimateResourceWeek(string weekId, string resourceId){
    return [SELECT ID, Hours__c   
              FROM CMC_Estimate_Resource_Week__c
              WHERE Estimate_Week__c = :weekId
              AND Estimate_Resource__c = :resourceId];
  }
  
  //method to get CMC_Estimate_Resource_Week__c records for set of week and resource Ids
  public static List<CMC_Estimate_Resource_Week__c> getEstimateResourceWeekRecords(Set<String>weekIds, Set<String>resourceIds){
    return [SELECT ID, Hours__c, Estimate_Resource__c, Estimate_Week__c   
              FROM CMC_Estimate_Resource_Week__c
              WHERE Estimate_Week__c IN :weekIds
              AND Estimate_Resource__c IN :resourceIds];
  }
  
  //method to get currencyISOcode for an estimate
  public static List<CMC_Presales_LOE__c> getCurrencyISOCodeonEstimate(String estimateId){
    return [SELECT CurrencyIsoCode 
              FROM CMC_Presales_LOE__c 
              WHERE Id = :estimateId];
  }
  
  //method to get CMC_Estimate_Week__c records for an estimateId
  public static List<CMC_Estimate_Week__c> getEstimateWeekRecords(String estimateId){
    return [SELECT Id, Date__c, Name, Order__c, Estimate__c, Phase__c, Milestone__c, E2_PhaseColorCode__c, E2_MilestoneColorCode__c
              , E2_Milestone1__c, E2_Milestone1ColorCode__c, E2_Milestone2__c, E2_Milestone2ColorCode__c 
              FROM CMC_Estimate_Week__c                                                    
              WHERE Estimate__c = :estimateId
              ORDER BY Date__c ASC, Order__c ASC];
  }
  
  
  
  //method to get CMC_Estimate_Resource__c and all Estimate_Resource_Week__c records for an estimateId 
  public static List<CMC_Estimate_Resource__c> getEstimateResourceAndResourceWeekRec(String estimateId){
    return [SELECT Id, Name, Cost__c, Estimate__c, Order__c, Rate__c, Role__c, E2_Role__c, Skill__c, E2_Estimate_Rate_Card__r.Resource_Role__c, E2_Estimate_Rate_Card__r.Region__c,
              (SELECT ID, Hours__c, Estimate_Week__c, Estimate_Resource__c
               FROM Estimate_Resource_Weeks__r)  
              FROM CMC_Estimate_Resource__c
              WHERE Estimate__c = :estimateId
              ORDER BY Order__c ASC];
  }
  
  //method to get CMC_Estimate_Resource__c for Skill updation for an estimateId and resourceId
  public static List<CMC_Estimate_Resource__c> getEstimateResourceForSkill(String estimateId, string resourceId){
      return [SELECT Id, Skill__c
              FROM CMC_Estimate_Resource__c
              WHERE Estimate__c = :estimateId
              AND id = : resourceId];
    
  }

}