src/objects/CMC_Estimate_Resource__c.object
<CustomObject>
    <fields>
        <fullName>E2_Estimate_Rate_Card__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to store the rate card reference of an estimate; This is a local reference to the estimate rate card record. Not used to display on the screen; Will be used only for reporting purpose.</description>
        <label>Estimate Rate Card</label>
        <referenceTo>E2_Estimate_Rate_Card__c</referenceTo>
        <relationshipLabel>Estimate Resources</relationshipLabel>
        <relationshipName>Estimate_Resources</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/CMC_Estimate_Resource_Week__c.object
<CustomObject>
    <label>Estimate Resource Week</label>
    <nameField>
        <displayFormat>ERW-{00000}</displayFormat>
        <label>CMC Estimate Resource Week Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Estimate Resource Weeks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CMC_Estimate_Week__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <description>The order the weeks are displayed in the Estimator</description>
        <inlineHelpText>The order the weeks are displayed in the Estimator</inlineHelpText>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Estimate Week</label>
    <nameField>
        <label>Week Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimate Weeks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CMC_Presales_LOE__c.object
<CustomObject>
</CustomObject>

src/objects/E2_Estimate_Rate_Card__c.object
<CustomObject>
    <description>Object stores cloned copy of rate card for all resources with modified bill rate of related presales estimate.</description>
    <fields>
        <fullName>Rate_Card__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rate Card</label>
        <referenceTo>pse__Rate_Card__c</referenceTo>
        <relationshipLabel>Estimate Rate Cards</relationshipLabel>
        <relationshipName>Estimate_Rate_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Resource region from rate card region lookup</description>
        <label>Region</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Resource_Role__c</fullName>
        <label>Resource Role</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Estimate Rate Card</label>
    <nameField>
        <displayFormat>ERC-{0000}</displayFormat>
        <label>Estimate Rate Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Estimate Rate Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/E2_System_setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom setting object to store estimator 2.0 system settings</description>
    <fields>
        <fullName>Timeline_Discounts__c</fullName>
        <label>Timeline Discounts</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>E2 System Settings</label>
</CustomObject>

src/classes/E2_TimelineSummaryControllerTest.cls
/**=====================================================================
 * Appirio, Inc
 * Name: E2_TimelineSummaryControllerTest
 * Description: Test class for E2_TimelineSummaryController apex class
 * Created Date: 2nd March, 2017
 * Created By: Jitendra Jangid (Appirio)
 * 
 * Date Modified      Modified By         Description of the update
 * Mar 02, 2017       Jitendra Jangid     S-467328: Generate summary from the all the timelines created.
*  =====================================================================*/

@isTest(seeAllData=false)
private class E2_TimelineSummaryControllerTest {

    public static CMC_Presales_LOE__c estimate;
    public static pse__Rate_Card__c rateCard;
    public static E2_Estimate_Rate_Card__c estimateRC;
    public static CMC_Estimate_Resource__c resource;
    public static CMC_Estimate_Week__c week;
    public static CMC_Estimate_Resource_Week__c resWeek;
    public static E2_System_setting__c e2SystemSetting;
  
    public static testMethod void testGetHourSummaryMap(){
	    
	   
	   
	    E2_TimelineSummaryController timelineController=new E2_TimelineSummaryController();
	    map<id, map<string, decimal>> mapHourSummary=timelineController.getHourSummaryMap();
	}
	
	@testSetup
	public static void testDataSetup(){
	    
	    e2SystemSetting = E2_System_setting__c.getInstance();
	    e2SystemSetting.Timeline_Discounts__c='5,10,15';
	    insert e2SystemSetting;
	     
        Account acc = E2_Test_Utils.insertAccount(true);
        Opportunity opp = E2_Test_Utils.insertOpportunity(acc.Id, true);
        Presales_Request__c psr = E2_Test_Utils.insertPresalesReq(opp.Id, 'Demo', false);
        insert psr;
        
        estimate = E2_Test_Utils.insertEstimate(psr.id, false);  
        insert estimate;
        
        pse__Region__c region = E2_Test_Utils.insertRegion(true);
        pse__Practice__c practice = E2_Test_Utils.insertPractice(true);
        
        rateCard = E2_Test_Utils.insertRateCard(acc.Id, region.Id, practice.Id, true);
        
        rateCard = E2_Test_Utils.insertRateCard(acc.Id, region.Id, practice.Id, false);
        rateCard.E2_Resource_Level__c='Senior Consultant';
        rateCard.pse__Role__c='QA Tester';
        insert rateCard;
        
        estimateRC = E2_Test_Utils.insertEstimateRateCard(estimate.Id, true);
        estimateRC = E2_Test_Utils.insertEstimateRateCard(estimate.Id, false);
        estimateRC.Resource_Level__c='Senior Consultant';
        estimateRC.Rate_Card__c=rateCard.ID;
        estimateRC.Resource_Role__c='QA Tester';
        estimateRC.Region__c='GS - North America Delivery';
        insert estimateRC;
        
        resource = E2_Test_Utils.insertCMCEstimateRes(estimate.Id, false);
        resource.E2_Estimate_Rate_Card__c=estimateRC.ID;
        insert resource;
        week = E2_Test_Utils.insertEstimateWeek(estimate.Id, false);
        week.Order__c = 3;
        insert week;
        resWeek = E2_Test_Utils.insertCMCEstimateResWeek(resource.Id, week.Id, true);
	}

}