src/objects/CMC_Presales_LOE__c.object
<CustomObject>
</CustomObject>

src/objects/E2_Scope__c.object
<CustomObject>
    <description>Estimator 2.0</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of this scope</description>
        <inlineHelpText>Description of this scope</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Parent_Scope__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent scope of this scope.</description>
        <inlineHelpText>(Optional) - Parent scope of this scope.</inlineHelpText>
        <label>Parent Scope</label>
        <referenceTo>E2_Scope__c</referenceTo>
        <relationshipName>Child_Scopes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Presales_LOE__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Relationship to Presales LOE</description>
        <inlineHelpText>Associated Estimate Record</inlineHelpText>
        <label>Estimate</label>
        <referenceTo>CMC_Presales_LOE__c</referenceTo>
        <relationshipName>E2_Scopes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scope_Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Contains the scopes relevant to the group.For eg: Sales cloud implementation with 100k records.</description>
        <inlineHelpText>Contains the scopes relevant to the group.For eg: Sales cloud implementation with 100k records.</inlineHelpText>
        <label>Scope Group</label>
        <referenceTo>E2_Scope_Group__c</referenceTo>
        <relationshipLabel>Scope</relationshipLabel>
        <relationshipName>Scopes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ultimate_Parent_Id__c</fullName>
        <formula>IF( NOT( ISBLANK( Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__c )),Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__c ,
IF( NOT(ISBLANK(Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__c)), Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__c,
IF(NOT(ISBLANK(Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__c)),
Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__c,
IF(NOT(ISBLANK(Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__c)),
Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__c,
IF(NOT(ISBLANK(Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__c)),Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__c,
IF(NOT(ISBLANK(Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__c)),
Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__c,
IF(NOT(ISBLANK(Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__c)), Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__c,
IF(NOT(ISBLANK(Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__c)), Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__c,
IF(NOT(ISBLANK(Parent_Scope__r.Parent_Scope__r.Parent_Scope__c)), Parent_Scope__r.Parent_Scope__r.Parent_Scope__c,
IF(NOT(ISBLANK(Parent_Scope__r.Parent_Scope__c)),Parent_Scope__r.Parent_Scope__c,
IF(NOT(ISBLANK(Parent_Scope__c)),Parent_Scope__c, NULL)))))))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This ID is used by Scope LOE Hrs calculation for all its child scopes</inlineHelpText>
        <label>Ultimate Parent Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ultimate_Parent_Scope__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the ultimate (topmost )scope that the current scope is pointing to.</description>
        <inlineHelpText>This is the ultimate i.e. the topmost scope that the current scope is pointing to.</inlineHelpText>
        <label>Ultimate Parent Scope</label>
        <referenceTo>E2_Scope__c</referenceTo>
        <relationshipName>E2_Scopes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Scope</label>
    <nameField>
        <label>Scope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scope</pluralLabel>
    <recordTypes>
        <fullName>Scope</fullName>
        <active>true</active>
        <description>Default Scope Record type. Mostly all scope should use this record type</description>
        <label>Scope</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/E2_Scope_Group__c.object
<CustomObject>
    <description>Estimator 2.0</description>
    <label>Scope Library</label>
    <nameField>
        <label>E2 Scope Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scope Library</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/E2_BatchUpdateUltimateParentScopeTest.cls
@isTest(seeAllData=false)
public class E2_BatchUpdateUltimateParentScopeTest {
  public static E2_Scope__c scopeParent1, scopeParent2;
  public static CMC_Presales_LOE__c estimate;
  public static Presales_Request__c psr;
  public static Id recTypeId1 = E2_RecordTypeClass.getId(E2_Constants.E2_SCOPE_API_NAME, E2_Constants.SCOPE_RT_SCOPE);
  
  // test method for insert
  public static testmethod void testScopeUltimateParent(){
    estimate = [SELECT Id FROM CMC_Presales_LOE__c]; 
    scopeParent1 = [SELECT ID FROM E2_Scope__c WHERE Parent_Scope__c = null];     
    scopeParent2 = [SELECT ID FROM E2_Scope__c WHERE Parent_Scope__c = :scopeParent1.Id];      
       
    User sysAdmin = E2_Test_Utils.insertUser(E2_Constants.PROFILE_SYS_ADMIN, true);
    psr =  [SELECT Id, Description__c, Name,Account_Name__c, Opportunity__r.Account.Id,Opportunity__c 
              FROM Presales_Request__c];
    
    E2_Scope__c scope =  E2_Test_Utils.insertScope(false);
    scope.recordTypeId = recTypeId1;
    scope.Presales_LOE__c = estimate.id;  
    scope.Parent_Scope__c = scopeParent2.Id;
    insert scope; 
       
    System.runAs(sysAdmin){
      //start test
      Test.startTest();
        E2_BatchUpdateUltimateParentScope batch = new E2_BatchUpdateUltimateParentScope();
        ID batchedprocessid = Database.executeBatch(batch);

      //stop test
      Test.stopTest();  
      
      E2_Scope__c resultScope = [SELECT Id, Ultimate_Parent_Scope__c, Ultimate_Parent_Id__c 
                                   From E2_Scope__c WHERE Id =: scope.Id];
      system.assertEquals(resultScope.Ultimate_Parent_Scope__c, scopeParent1.Id);                             
    }    
  }
  
  //create test data
  @testSetup 
  public static void createTestData(){
    Account acc;
    Opportunity opp;
          
    acc = E2_Test_Utils.insertAccount(true);
    opp = E2_Test_Utils.insertOpportunity(acc.Id, true);
    
    psr = E2_Test_Utils.insertPresalesReq(opp.Id, 'Demo', false);
    insert psr;
    
    estimate = E2_Test_Utils.insertEstimate(psr.id, false);  
    insert estimate;
    
    E2_Scope_Group__c scopeGroup = E2_Test_Utils.insertScopeGroup(true);  
      
    scopeParent1 =  E2_Test_Utils.insertScope(false);
    scopeParent1.recordTypeId = recTypeId1;
    scopeParent1.Presales_LOE__c = estimate.id;  
    scopeParent1.Scope_Group__c = scopeGroup.id;
    insert scopeParent1;
    
    scopeParent2 =  E2_Test_Utils.insertScope(false);
    scopeParent2.recordTypeId = recTypeId1;
    scopeParent2.Presales_LOE__c = estimate.id;  
    scopeParent2.Scope_Group__c = scopeGroup.id;
    scopeParent2.Parent_Scope__c = scopeParent1.Id;
    insert scopeParent2;
    
  }
}