src/objects/CMC_Presales_LOE__c.object
<CustomObject>
</CustomObject>

src/objects/E2_Scope__c.object
<CustomObject>
    <description>Estimator 2.0</description>
    <fields>
        <fullName>Complexity__c</fullName>
        <description>Complexity (High, Medium, Low)</description>
        <globalPicklist>E2_Complexity</globalPicklist>
        <inlineHelpText>Complexity of this scope(High, Medium, Low)</inlineHelpText>
        <label>Complexity</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Is_Favourite__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When marked by the SA as favorite ,the SA can find the same in the &quot;My Scope&quot; section when adds a scope from template.</description>
        <inlineHelpText>When marked by the SA as favorite ,the SA can find the same in the &quot;My Scope&quot; section when adds a scope from template.</inlineHelpText>
        <label>Is Favourite</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Scope__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent scope of this scope.</description>
        <inlineHelpText>(Optional) - Parent scope of this scope.</inlineHelpText>
        <label>Parent Scope</label>
        <referenceTo>E2_Scope__c</referenceTo>
        <relationshipName>Child_Scopes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Presales_LOE__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Relationship to Presales LOE</description>
        <inlineHelpText>Associated Estimate Record</inlineHelpText>
        <label>Estimate</label>
        <referenceTo>CMC_Presales_LOE__c</referenceTo>
        <relationshipName>E2_Scopes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scope_Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Contains the scopes relevant to the group.For eg: Sales cloud implementation with 100k records.</description>
        <inlineHelpText>Contains the scopes relevant to the group.For eg: Sales cloud implementation with 100k records.</inlineHelpText>
        <label>Scope Group</label>
        <referenceTo>E2_Scope_Group__c</referenceTo>
        <relationshipLabel>Scope</relationshipLabel>
        <relationshipName>Scopes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Scope</label>
    <nameField>
        <label>Scope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scope</pluralLabel>
    <recordTypes>
        <fullName>Scope</fullName>
        <active>true</active>
        <description>Default Scope Record type. Mostly all scope should use this record type</description>
        <label>Scope</label>
    </recordTypes>
    <recordTypes>
        <fullName>Template</fullName>
        <active>true</active>
        <description>This is used by the Scope Template Managers as they are building out the template used in scoping of presales estimates.</description>
        <label>Template</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/E2_Scope_Group__c.object
<CustomObject>
    <description>Estimator 2.0</description>
    <label>Scope Library</label>
    <nameField>
        <label>E2 Scope Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scope Library</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/E2_SelectScopeTemplateControllerTest.cls
@isTest(seeAllData=false)
public class E2_SelectScopeTemplateControllerTest {
  public static E2_Scope__c scopeTemplate, favScope;
  public static CMC_Presales_LOE__c estimate;
  public static Id rtTemplateId = E2_RecordTypeClass.getId('E2_Scope__c', E2_Constants.SCOPE_RT_TEMPLATE);
  public static Id rtScopeId = E2_RecordTypeClass.getId('E2_Scope__c', E2_Constants.SCOPE_RT_SCOPE);
  public static E2_Scope_Group__c scopeGroup;
  public static User sysAdmin;
  
  public static testmethod void testSelectScope1(){
    Profile p = [SELECT id from profile where name =: E2_Constants.PROFILE_SYS_ADMIN ];
    sysAdmin = new User();
    sysAdmin.Id = UserInfo.getUserId(); //E2_Test_Utils.insertUser(E2_Constants.PROFILE_SYS_ADMIN, true);
    sysAdmin.profileid = p.Id;
    update sysAdmin;
    
    scopeTemplate = [SELECT Id FROM E2_Scope__c WHERE RecordTypeId = :rtTemplateId];
    favScope = [SELECT Id FROM E2_Scope__c WHERE RecordTypeId = :rtScopeId];
    scopeGroup = [SELECT Id, Name FROM E2_Scope_Group__c];
    System.runAs(sysAdmin){
    Test.startTest();
      PageReference pageRef = Page.E2_AddNewScope;
      Test.setCurrentPage(pageRef);
      E2_SelectScopeTemplateController controller = new E2_SelectScopeTemplateController();
      controller.pageAction();
      controller.scopeName = null;
      controller.sortDirection = null;
      system.assertEquals(controller.scopeName, '');
      controller.scopeGroups = null;
      List<SelectOption> scopeGroups;
      system.assert(controller.scopeGroups.size() == 1);
      controller.selectedPageNumber = 3;
      //sort the result
      controller.sortExpression = null;
      controller.getSortDirection();
      system.assertEquals(controller.sortDirection, 'ByAsc');
      controller.sortDirection = 'ByAsc';
      system.assertEquals(controller.sortExpression, null);
      controller.sortList();
      controller.selectedCon = 1;
      controller.isTemplatePage = false;
      //asserts to get the result
      system.assertEquals(controller.scopeList.size(), 1, '1 Scope Template record not loaded');
      system.assertEquals(controller.favScopeList.size(), 1, '1 Scope record not loaded');
      //system.assertEquals(controller.conList.size(), 2, 'Scope records not in selection listd');
      //search by complexity
      controller.scopeName = '';
      controller.searchScopeRecords();
      controller.getList();
       controller.selectedCon = 1;
      controller.getList();
      //asserts to get the result
      system.assert(controller.scopeList.size() > 0);
      system.assert(controller.favScopeList.size() > 0);
      //sort the result
      controller.sortExpression = 'ByScopeName';
      controller.getSortDirection();
      controller.sortDirection = 'ByAsc';
      controller.sortList();
      
      //search by scope name
      controller.scopeName = 'Test Scope';
      controller.searchScopeRecords();
      
      controller.getList();
      system.assert(controller.scopeList.size() > 0);
      system.assert(controller.favScopeList.size() > 0); 
      
      //sort the result
      controller.sortExpression = 'ByComplexity';
      controller.sortExpression = 'ByComplexity';
      controller.sortDirection = 'ByAsc';
      controller.sortList();
      controller.sortExpression = 'ByGroup';
      controller.sortDirection = 'ByAsc';
      controller.sortList();
      controller.sortExpression = 'ByEfforts';
      controller.sortDirection = 'ByDesc';
      controller.sortList();
      
      controller.resetResults();

      Test.stopTest(); 
    }
      
     
  }

  
   @testSetup
  private static void createTestData(){
    Account acc = E2_Test_Utils.insertAccount(true);
    Opportunity opp = E2_Test_Utils.insertOpportunity(acc.Id, true);
    
    Presales_Request__c psr = E2_Test_Utils.insertPresalesReq(opp.Id, 'Demo', true);
    estimate = E2_Test_Utils.insertEstimate(psr.Id, true);
    
    scopeGroup = E2_Test_Utils.insertScopeGroup(true);
    
    scopeTemplate = E2_Test_Utils.insertScope(false);
    //scopeTemplate.Presales_LOE__c = estimate.Id;
    scopeTemplate.RecordTypeId = rtTemplateId;
    scopeTemplate.Parent_Scope__c = null;
    scopeTemplate.Complexity__c = 'Low';
    insert scopeTemplate;
    

    favScope = E2_Test_Utils.insertScope(false);
    favScope.Presales_LOE__c = estimate.Id;
    favScope.RecordTypeId = rtScopeId;
    favScope.Is_Favourite__c = true;
    favScope.Complexity__c = 'Medium';
    favScope.OwnerId = UserInfo.getUserId();
    favScope.Scope_Group__c = scopeGroup.Id;
    insert favScope;
    system.debug('====favScope>>' +favScope); 
    
    
  }

}