src/objects/CMC_Presales_LOE__c.object
<CustomObject>
</CustomObject>

src/objects/E2_Favourite_Scope__c.object
<CustomObject>
    <description>Estimator 2.0: This is a junction object between User and E2_Scope__c to store details when a template is marked as favorite.</description>
    <fields>
        <fullName>Scope__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scope</label>
        <referenceTo>E2_Scope__c</referenceTo>
        <relationshipLabel>Favorite Scopes</relationshipLabel>
        <relationshipName>E2_Favourite_Scope</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Favorite Scope</label>
    <nameField>
        <displayFormat>E2FS-{0000}</displayFormat>
        <label>Favorite Scope Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Favorite Scopes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/E2_Scope__c.object
<CustomObject>
    <description>Estimator 2.0</description>
    <fields>
        <fullName>Is_Favourite__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When marked by the SA as favorite ,the SA can find the same in the &quot;My Scope&quot; section when adds a scope from template.</description>
        <inlineHelpText>When marked by the SA as favorite ,the SA can find the same in the &quot;My Scope&quot; section when adds a scope from template.</inlineHelpText>
        <label>Is Favourite</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Presales_LOE__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Relationship to Presales LOE</description>
        <inlineHelpText>Associated Estimate Record</inlineHelpText>
        <label>Estimate</label>
        <referenceTo>CMC_Presales_LOE__c</referenceTo>
        <relationshipName>E2_Scopes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scope_Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Contains the scopes relevant to the group.For eg: Sales cloud implementation with 100k records.</description>
        <inlineHelpText>Contains the scopes relevant to the group.For eg: Sales cloud implementation with 100k records.</inlineHelpText>
        <label>Scope Group</label>
        <referenceTo>E2_Scope_Group__c</referenceTo>
        <relationshipLabel>Scope</relationshipLabel>
        <relationshipName>Scopes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Scope</label>
    <nameField>
        <label>Scope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scope</pluralLabel>
    <recordTypes>
        <fullName>Scope</fullName>
        <active>true</active>
        <description>Default Scope Record type. Mostly all scope should use this record type</description>
        <label>Scope</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/E2_Scope_Group__c.object
<CustomObject>
    <description>Estimator 2.0</description>
    <label>Scope Library</label>
    <nameField>
        <label>E2 Scope Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scope Library</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/E2_BatchCreateFavoriteScopeTest.cls
@isTest(seeAllData=false)
public class E2_BatchCreateFavoriteScopeTest {
  public static CMC_Presales_LOE__c estimate;
  public static Presales_Request__c psr;
  public static Id recTypeId1 = E2_RecordTypeClass.getId(E2_Constants.E2_SCOPE_API_NAME, E2_Constants.SCOPE_RT_SCOPE);
  public static List<E2_Scope__c> scopeLst;
  
  
  //
  public static testmethod void testBatch(){
    estimate = [SELECT Id FROM CMC_Presales_LOE__c]; 
    scopeLst = [SELECT Id FROM E2_Scope__c];
    User sysAdmin = E2_Test_Utils.insertUser(E2_Constants.PROFILE_SYS_ADMIN, true);
    
    System.runAs(sysAdmin){
	    //start test
	    Test.startTest();
	       E2_BatchCreateFavoriteScope batch = new E2_BatchCreateFavoriteScope();
         ID batchedprocessid = Database.executeBatch(batch);
	    
	    //stop test
	    Test.stopTest();
	    List<E2_Favourite_Scope__c> favScopes = [SELECT Id FROM E2_Favourite_Scope__c WHERE Scope__c IN :scopeLst];
	    system.assertEquals(favScopes.size(), 10, '10 Favourite Scope are created');
    }
  }
  
  //create test data
  @testSetup 
  public static void createTestData(){
    Account acc;
    Opportunity opp;
          
    acc = E2_Test_Utils.insertAccount(true);
    opp = E2_Test_Utils.insertOpportunity(acc.Id, true);
    
    psr = E2_Test_Utils.insertPresalesReq(opp.Id, 'Demo', false);
    insert psr;
    
    estimate = E2_Test_Utils.insertEstimate(psr.id, false);  
    insert estimate;
    
    E2_Scope_Group__c scopeGroup = E2_Test_Utils.insertScopeGroup(true);  
    
    scopeLst = new List<E2_Scope__c>();
    E2_Scope__c scope;
    
    for(integer i=1; i<=10; i++){  
	    scope =  E2_Test_Utils.insertScope(false);
	    scope.Name = 'Test Scope'+i;
	    scope.recordTypeId = recTypeId1;
	    scope.Presales_LOE__c = estimate.id;  
	    scope.Scope_Group__c = scopeGroup.id;
	    scope.Is_Favourite__c = true;
      scopeLst.add(scope);
    }
    
    for(integer i=1; i<=4; i++){
      scope =  E2_Test_Utils.insertScope(false);
      scope.Name = 'Test Scope'+i;
      scope.recordTypeId = recTypeId1;
      scope.Presales_LOE__c = estimate.id;  
      scope.Scope_Group__c = scopeGroup.id;
      scope.Is_Favourite__c = false;
      scopeLst.add(scope);
    }
    
    insert scopeLst;
    
    
    
  }

}