src/objects/CMC_Presales_LOE__c.object
<CustomObject>
    <fields>
        <fullName>E2_Derived_Effort_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Points to the Derived effort group whose derived efforts templates are used in the estimate.</description>
        <inlineHelpText>Points to the Derived effort group whose derived efforts templates are used in the estimate.</inlineHelpText>
        <label>Derived Effort Template</label>
        <referenceTo>E2_Derived_Effort_Group__c</referenceTo>
        <relationshipLabel>Presales LOEs</relationshipLabel>
        <relationshipName>Presales_LOEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>E2_Last_Build_Datetime__c</fullName>
        <label>Last Build Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>E2_Risk__c</fullName>
        <label>Risk %</label>
        <picklist>
            <picklistValues>
                <fullName>0%</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>5%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>75%</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/E2_Derived_Effort__c.object
<CustomObject>
    <description>Estimator 2.0</description>
    <fields>
        <fullName>Include_When_Hours__c</fullName>
        <label>Include When Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Include_When__c</fullName>
        <label>Include When</label>
        <picklist>
            <picklistValues>
                <fullName>always</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>hours exceed or equals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>hours are less than</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Presales_LOE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relationship to Estimate object</description>
        <inlineHelpText>Relationship to Estimate object</inlineHelpText>
        <label>Estimate</label>
        <referenceTo>CMC_Presales_LOE__c</referenceTo>
        <relationshipName>E2_Derived_Efforts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Derived Effort</label>
    <nameField>
        <label>Derived Effort Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Derived Effort</pluralLabel>
    <recordTypes>
        <fullName>Template</fullName>
        <active>true</active>
        <description>This is used by the Derived Effort Template Managers as they are building out the template used in calculating efforts on Estimate level.</description>
        <label>Template</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/E2_Derived_Effort_Group__c.object
<CustomObject>
    <description>Estimator 2.0</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Derived Effort Templates</label>
    <nameField>
        <label>Derived Effort Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Derived Effort Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/E2_Effort__c.object
<CustomObject>
    <description>Estimator 2.0</description>
    <fields>
        <fullName>Speciality__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The skill needed in particular to implement the scope details.</description>
        <inlineHelpText>The skill needed in particular to implement the scope details.</inlineHelpText>
        <label>Speciality</label>
        <referenceTo>pse__Skill__c</referenceTo>
        <relationshipName>E2_Efforts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Effort</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Efforts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/E2_Scope__c.object
<CustomObject>
    <description>Estimator 2.0</description>
    <fields>
        <fullName>Complexity__c</fullName>
        <description>Complexity (High, Medium, Low)</description>
        <globalPicklist>E2_Complexity</globalPicklist>
        <inlineHelpText>Complexity of this scope(High, Medium, Low)</inlineHelpText>
        <label>Complexity</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of this scope</description>
        <inlineHelpText>Description of this scope</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Parent_Scope__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent scope of this scope.</description>
        <inlineHelpText>(Optional) - Parent scope of this scope.</inlineHelpText>
        <label>Parent Scope</label>
        <referenceTo>E2_Scope__c</referenceTo>
        <relationshipName>Child_Scopes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Presales_LOE__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Relationship to Presales LOE</description>
        <inlineHelpText>Associated Estimate Record</inlineHelpText>
        <label>Estimate</label>
        <referenceTo>CMC_Presales_LOE__c</referenceTo>
        <relationshipName>E2_Scopes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scope_Item_Type__c</fullName>
        <inlineHelpText>Optional Field that you can use to specify if a scope item should be considered as an Epic, Story or Component.  This will allow you to filter when exporting to CMC.</inlineHelpText>
        <label>Scope Item Type</label>
        <picklist>
            <picklistValues>
                <fullName>Component</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Epic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Story</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capability</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Ultimate_Parent_Scope__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the ultimate (topmost )scope that the current scope is pointing to.</description>
        <inlineHelpText>This is the ultimate i.e. the topmost scope that the current scope is pointing to.</inlineHelpText>
        <label>Ultimate Parent Scope</label>
        <referenceTo>E2_Scope__c</referenceTo>
        <relationshipName>E2_Scopes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Scope</label>
    <nameField>
        <label>Scope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scope</pluralLabel>
    <recordTypes>
        <fullName>Scope</fullName>
        <active>true</active>
        <description>Default Scope Record type. Mostly all scope should use this record type</description>
        <label>Scope</label>
    </recordTypes>
    <recordTypes>
        <fullName>Template</fullName>
        <active>true</active>
        <description>This is used by the Scope Template Managers as they are building out the template used in scoping of presales estimates.</description>
        <label>Template</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/E2_CapacityControllerTest.cls
/**=====================================================================
 * Appirio, Inc
 * Name: E2_CapacityController
 * Description: Controller class to build & display estimate capacity
 * Created Date: July 07, 2016
 * Created By: Rohit Sharma (Appirio)
 * 
 * Date Modified      Modified By                  Description of the update
 * Oct 17, 2016       Jitendra Jangid              S-447214 : Show capacity distribution by Epics.
*  =====================================================================*/


@isTest(seeAllData=false)
public class E2_CapacityControllerTest {
    
  public static testmethod void testCapacity(){
      
    User sysAdmin = E2_Test_Utils.insertUser(E2_Constants.PROFILE_SYS_ADMIN, true);
    
    System.runAs(sysAdmin){
        Test.startTest();
            CMC_Presales_LOE__c estimate = [SELECT Id,E2_Last_Build_Datetime__c,E2_Derived_Effort_Template__c, E2_Risk__c
                                              FROM CMC_Presales_LOE__c];
            PageReference pageRef = Page.E2_Capacity;
            Test.setCurrentPage(pageRef);
            ApexPages.StandardController stdController = new ApexPages.StandardController(estimate);
            E2_CapacityController controller = new E2_CapacityController(stdController);
            controller.buildCapacity();
            controller.pageAction();
            system.assertEquals(controller.phases.size(), 1);
        system.assertEquals(controller.skillsPhases.size(), 1);
        Test.stopTest();  
     }
  }
  
  
  
  //create test data
  @testSetup
  private static void createTestData(){
    E2_Derived_Effort_Group__c derivedEffGrp  = E2_Test_Utils.insertDerivedEffort(false);
    derivedEffGrp.Description__c = 'Calculate Capacity';
    insert derivedEffGrp;
    List<E2_Derived_Effort__c> derivedEfforts = new List<E2_Derived_Effort__c>();
    Id devRecordTypeId = Schema.SObjectType.E2_Derived_Effort__c.getRecordTypeInfosByName().get('Template').getRecordTypeId();
    
    E2_Derived_Effort__c objDerviedEffort_1=E2_Test_Utils.insertDerivedEffort('Project Manager', 'Build', 'Project Manager', 'Build', devRecordTypeId, derivedEffGrp.Id, false);
    objDerviedEffort_1.Include_When__c='hours exceed or equals';
    objDerviedEffort_1.Include_When_Hours__c=40;
    derivedEfforts.add(objDerviedEffort_1);
    
    E2_Derived_Effort__c objDerviedEffort_2=E2_Test_Utils.insertDerivedEffort('Project Manager', 'Build', 'Project Manager', Null, devRecordTypeId, derivedEffGrp.Id, false);
    objDerviedEffort_2.Include_When__c='hours are less than';
    objDerviedEffort_2.Include_When_Hours__c=45;
    derivedEfforts.add(objDerviedEffort_2);
    
    derivedEfforts.add(E2_Test_Utils.insertDerivedEffort('Project Manager', 'Build', Null, 'Build', devRecordTypeId, derivedEffGrp.Id, false));
    derivedEfforts.add(E2_Test_Utils.insertDerivedEffort('Project Manager', 'Build', Null, Null, devRecordTypeId, derivedEffGrp.Id, false));
    insert derivedEfforts;
    
    
    Account acc = E2_Test_Utils.insertAccount(true);
    Opportunity opp = E2_Test_Utils.insertOpportunity(acc.Id, true);    
    Presales_Request__c psr = E2_Test_Utils.insertPresalesReq(opp.Id, 'Demo', true);
    CMC_Presales_LOE__c estimate = E2_Test_Utils.insertEstimate(psr.Id, false); 
    estimate.E2_Derived_Effort_Template__c = derivedEffGrp.Id;
    estimate.E2_Risk__c = '10%'; 
    insert estimate;
    
    E2_Scope__c scope = E2_Test_Utils.insertScope(false);
    List<E2_Scope__c> scopeLst = new List<E2_Scope__c>();
    scope.Presales_LOE__c = estimate.Id;
    scopeLst.add(scope);
    E2_Scope__c scope1 = E2_Test_Utils.insertScope(false);
    scope1.Presales_LOE__c = estimate.Id;
    scope1.Complexity__c = 'high';
    scope1.Parent_Scope__c=scope.Id;
    scope1.Ultimate_Parent_Scope__c=scope.Id;
    scopeLst.add(scope1);
    E2_Scope__c scope2 = E2_Test_Utils.insertScope(false);
    scope2.Presales_LOE__c = estimate.Id;
    scope2.Complexity__c = 'low';
    scope2.Scope_Item_Type__c='Epic';
    scope2.Parent_Scope__c=scope1.Id;
    scope2.Ultimate_Parent_Scope__c=scope.Id;
    scopeLst.add(scope2);
    
    E2_Scope__c scope3 = E2_Test_Utils.insertScope(false);
    scope3.Presales_LOE__c = estimate.Id;
    scope3.Scope_Item_Type__c='Epic';
    scope3.Complexity__c = 'high';
    scopeLst.add(scope3);
    insert scopeLst;
    
    pse__Skill__c skill = new pse__Skill__c(Name = 'Javascript',pse__Type__c = 'Technologies',pse__Skill_Or_Certification__c = 'skill');
    insert skill; 
    E2_Effort__c effort1 = E2_Test_Utils.insertEffort(false, scopeLst[0].Id);
    effort1.Speciality__c = skill.Id;
    E2_Effort__c effort2 = E2_Test_Utils.insertEffort(false, scopeLst[1].Id);
    E2_Effort__c effort3 = E2_Test_Utils.insertEffort(false, scopeLst[2].Id);
    E2_Effort__c effort4 = E2_Test_Utils.insertEffort(false, scopeLst[3].Id);
    List<E2_Effort__c> effortLst = new List<E2_Effort__c>();
    effortLst.add(effort1);
    effortLst.add(effort2);
    effortLst.add(effort3);
    effortLst.add(effort4);
    insert effortLst;
      
    
    
  }

}