src/objects/CMC_Presales_LOE__c.object
<CustomObject>
</CustomObject>

src/objects/E2_Estimate_Milestone__c.object
<CustomObject>
    <description>This object is used to store all the milestone details associated with a presales estimate. Related to Estimator 2.0 App</description>
    <label>Estimate Milestone</label>
    <nameField>
        <displayFormat>EM-{0000000000}</displayFormat>
        <label>Estimate Milestone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Estimate Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/E2_Estimate_Milestone_Week__c.object
<CustomObject>
    <description>Junction object between Estimate Milestone and Estimate Week. Used in Estimator 2.0 App</description>
    <label>Estimate Milestone Week</label>
    <nameField>
        <displayFormat>EMW-{0000000000}</displayFormat>
        <label>Estimate Milestone Week Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Estimate Milestone Weeks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/E2_Estimate_Week_Milestone__c.object
<CustomObject>
    <label>Estimate Week Milestone</label>
    <nameField>
        <label>Week Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimate Week Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/E2_Milestone_Library__c.object
<CustomObject>
    <label>Milestone Library</label>
    <nameField>
        <label>Milestone Library Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestone Library</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/E2_Timeline_Milestone__c.object
<CustomObject>
    <fields>
        <fullName>E2_Milestone_Library__c</fullName>
        <label>Milestone Library</label>
        <referenceTo>E2_Milestone_Library__c</referenceTo>
        <relationshipLabel>Timeline Milestones</relationshipLabel>
        <relationshipName>Timeline_Milestone</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Timeline Milestone</label>
    <nameField>
        <displayFormat>TM-{00000}</displayFormat>
        <label>Timeline_Milestone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timeline Milestone</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/E2_MilestoneDataUtil_WSTest.cls
@isTest(seeAllData = false)
public class E2_MilestoneDataUtil_WSTest{
    public static CMC_Presales_LOE__c estimate;
    public static E2_Estimate_Week_Milestone__c week;
    public static E2_Estimate_Milestone__c milestone;
    public static E2_Estimate_Milestone_Week__c milestoneWeek;
    public static E2_Milestone_Library__c milestoneLib;
    public static E2_Timeline_Milestone__c timelineMilestone;
    
    public static testmethod void testEstimateMilestone(){
      User sysAdmin = E2_Test_Utils.insertUser(E2_Constants.PROFILE_SYS_ADMIN, true);
      System.runAs(sysAdmin){
        Test.startTest();
        estimate = [SELECT Id FROM CMC_Presales_LOE__c ];
        system.assertEquals(E2_MilestoneDataUtil_WS.getEstimateMilestones(estimate.Id).size(), 1);
        Test.stopTest();
      }
    }
    
    public static testmethod void testMilestoneWeek(){
      User sysAdmin = E2_Test_Utils.insertUser(E2_Constants.PROFILE_SYS_ADMIN, true);
      System.runAs(sysAdmin){
        Test.startTest();
        week = [SELECT Id FROM E2_Estimate_Week_Milestone__c ];
        milestone = [SELECT Id FROM E2_Estimate_Milestone__c ];
        Set<String> weekIds = new Set<String>();
        weekIds.add(week.Id);
        Set<String> milestoneIds = new Set<String>();
        milestoneIds.add(milestone.Id);
        system.assertEquals(E2_MilestoneDataUtil_WS.getEstimateMilestoneWeeks(weekIds, milestoneIds).size(), 1);
        system.assertEquals(E2_MilestoneDataUtil_WS.getEstimateMilestoneWeeksforWeek(week.Id, milestone.Id).size(), 1);
        Test.stopTest();
      }
    }
    
    public static testmethod void testMilestone(){
      User sysAdmin = E2_Test_Utils.insertUser(E2_Constants.PROFILE_SYS_ADMIN, true);
      System.runAs(sysAdmin){
        Test.startTest();
        estimate = [SELECT Id FROM CMC_Presales_LOE__c ];
        milestone = [SELECT Id FROM E2_Estimate_Milestone__c ];
        system.assertEquals(E2_MilestoneDataUtil_WS.getMilestone(estimate.Id, milestone.Id).size(), 1);
        Test.stopTest();
      }
    }
    
    public static testmethod void testEstimateWeekMilestone(){
      User sysAdmin = E2_Test_Utils.insertUser(E2_Constants.PROFILE_SYS_ADMIN, true);
      System.runAs(sysAdmin){
        Test.startTest();
        estimate = [SELECT Id FROM CMC_Presales_LOE__c ];
        milestone = [SELECT Id FROM E2_Estimate_Milestone__c ];
        system.assertEquals(E2_MilestoneDataUtil_WS.getEstimateMilestoneAndAllWeeks(estimate.Id).size(), 1);
        Test.stopTest();
      }
    }
    
    public static testmethod void testMilestonelib(){
      User sysAdmin = E2_Test_Utils.insertUser(E2_Constants.PROFILE_SYS_ADMIN, true);
      System.runAs(sysAdmin){
        Test.startTest();
        milestoneLib = [SELECT Id FROM E2_Milestone_Library__c ];
        system.assertEquals(E2_MilestoneDataUtil_WS.getTimelineMilestones(milestoneLib.Id).size(), 1);
        Test.stopTest();
      }
    }
    
    @testSetup
    private static void createTestData(){
        Account acc = E2_Test_Utils.insertAccount(true);
        Opportunity opp = E2_Test_Utils.insertOpportunity(acc.Id, true);        
        Presales_Request__c psr = E2_Test_Utils.insertPresalesReq(opp.Id, 'Demo', true);
        estimate = E2_Test_Utils.insertEstimate(psr.Id, true);
        
        week = E2_Test_Utils.insertEstimateWeekMilestone(estimate.Id, true);
        milestone = E2_Test_Utils.insertEstimateMilestone(estimate.Id, true);
        milestoneWeek = E2_Test_Utils.insertMilestoneWeek(milestone.Id, week.Id, true);
        milestoneLib = E2_Test_Utils.insertMilestoneLibrary(true);
        timelineMilestone = E2_Test_Utils.insertTimelineMilestone (milestoneLib.Id, true);
    }    


}