src/objects/E2_Effort__c.object
<CustomObject>
    <description>Estimator 2.0</description>
    <fields>
        <fullName>Complexity_Factor_High__c</fullName>
        <description>If no value, High or Low factors simply do not act on orignal effort (in some cases, this is logical)</description>
        <inlineHelpText>Adds this % to original LOE when Scope Complexity = High</inlineHelpText>
        <label>Complexity Adder</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Complexity_Factor_Low__c</fullName>
        <description>If no value, High or Low factors simply do not act on orignal effort (in some cases, this is logical)</description>
        <inlineHelpText>Subtracts this % from original LOE when Scope Complexity = Low</inlineHelpText>
        <label>Simplification Subtractor</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Effort_Hrs__c</fullName>
        <description>Where hours end up.The number of hours needed to implement the scope&apos;s functionality.</description>
        <inlineHelpText>Assumes &quot;Medium&quot; Complexity Effort.</inlineHelpText>
        <label>Effort (Hrs)</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is this effort active?</description>
        <inlineHelpText>Is this effort active?</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <description>In what Phase....</description>
        <globalPicklist>E2_Phases</globalPicklist>
        <inlineHelpText>During which Phase is this effort expended?</inlineHelpText>
        <label>Phase</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Resource_Role__c</fullName>
        <description>Same picklist values as are available throughout the rest of our systems (Role/ResourceRole): Rate Card reference here https://appirio.my.salesforce.com/00N50000001v03g?setupid=CustomObjects</description>
        <globalPicklist>E2_Role</globalPicklist>
        <inlineHelpText>Aligned with Rate Card Roles</inlineHelpText>
        <label>Resource Role</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Scope__c</fullName>
        <description>Parent Scope</description>
        <inlineHelpText>Parent Scope</inlineHelpText>
        <label>Scope</label>
        <referenceTo>E2_Scope__c</referenceTo>
        <relationshipName>Efforts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Effort</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Efforts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/E2_Scope__c.object
<CustomObject>
    <description>Estimator 2.0</description>
    <fields>
        <fullName>Complexity__c</fullName>
        <description>Complexity (High, Medium, Low)</description>
        <globalPicklist>E2_Complexity</globalPicklist>
        <inlineHelpText>Complexity of this scope(High, Medium, Low)</inlineHelpText>
        <label>Complexity</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is this scope active?</description>
        <inlineHelpText>Is this scope active?</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Scope__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent scope of this scope.</description>
        <inlineHelpText>(Optional) - Parent scope of this scope.</inlineHelpText>
        <label>Parent Scope</label>
        <referenceTo>E2_Scope__c</referenceTo>
        <relationshipName>Child_Scopes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scope_Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Contains the scopes relevant to the group.For eg: Sales cloud implementation with 100k records.</description>
        <inlineHelpText>Contains the scopes relevant to the group.For eg: Sales cloud implementation with 100k records.</inlineHelpText>
        <label>Scope Group</label>
        <referenceTo>E2_Scope_Group__c</referenceTo>
        <relationshipLabel>Scope</relationshipLabel>
        <relationshipName>Scopes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Scope</label>
    <nameField>
        <label>Scope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scope</pluralLabel>
    <recordTypes>
        <fullName>Scope</fullName>
        <active>true</active>
        <description>Default Scope Record type. Mostly all scope should use this record type</description>
        <label>Scope</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/E2_Scope_Group__c.object
<CustomObject>
    <description>Estimator 2.0</description>
    <label>Scope Library</label>
    <nameField>
        <label>E2 Scope Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scope Library</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/E2_AddNewScopeTemplateControllerTest.cls
@isTest(SeeAllData=false)
private class E2_AddNewScopeTemplateControllerTest {

    public static E2_Scope_Group__c scopeGrp;
  public static E2_Scope__c scope;
  public static List<E2_Effort__c> effortLst;  
  public static Id recTypeId = E2_RecordTypeClass.getId('E2_Scope__c', E2_Constants.SCOPE_RT_TEMPLATE);
  public static Presales_Request__c psr;
  
  public static testmethod void testViewScope(){
    scope = [SELECT Id FROM E2_Scope__c WHERE Parent_Scope__c = null];
    scopeGrp = [SELECT Id FROM E2_Scope_Group__c limit 1];
    effortLst = [SELECT Id FROM E2_Effort__c WHERE Scope__c = :scope.Id];
    
    //create sys admin user
    User sysAdmin = E2_Test_Utils.insertUser(E2_Constants.PROFILE_SYS_ADMIN, true);
    
    System.runAs(sysAdmin){
        //start test
        Test.startTest();    
        PageReference pageRef = Page.E2_AddNewScopeTemplate;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('scopegroup_id', scopeGrp.Id);
        ApexPages.currentPage().getParameters().put(E2_Constants.URL_KEY_IS_VIEW, 'true');
        ApexPages.StandardController stdController = new ApexPages.StandardController(scope);
        E2_AddNewScopeTemplateController controller = new E2_AddNewScopeTemplateController(stdController);
    
       
      controller.pageAction();
      system.assert(controller.is_View == true);
      ApexPages.currentPage().getParameters().remove('scopegroup_id');
      ApexPages.currentPage().getParameters().remove(E2_Constants.URL_KEY_IS_VIEW);
      
      ApexPages.currentPage().getParameters().put('scopegroup_id', scopeGrp.Id);
      ApexPages.currentPage().getParameters().put(E2_Constants.URL_KEY_IS_EDIT, 'true');
      stdController = new ApexPages.StandardController(scope);
      controller = new E2_AddNewScopeTemplateController(stdController); 
      controller.pageAction();
      system.assert(controller.is_Edit == true);
      
      System.assertEquals(controller.childScopes.size(), 1, '1 child scope should be added in list as master');     
      
      E2_AddNewScopeTemplateController.Scope scope_wrap = controller.childScopes[0];
      scope_wrap.addNewEffort();
      scope_wrap.addNewEffort();
      for(E2_AddNewScopeTemplateController.Effort eff: scope_wrap.efforts){
            
          eff.effort.Is_Active__c = true;
          eff.effort.Effort_Hrs__c = 40;
          eff.effort.Phase__c = 'Build';
          eff.effort.Resource_Role__c = 'Project Manager';
          eff.effort.Complexity_Factor_High__c = 10;
          eff.effort.Complexity_Factor_Low__c = 10;
             
      }  
      System.assertEquals(scope_wrap.getEffortsSize(), 120, 'scope cumulative efforts size should match'); 
      scope_wrap.reload();
      scope_wrap.changeComplexity(); 
        
      controller.saveScope();  
      Set<Id>  childScopeIds = new Set<Id>();                
        for(E2_Scope__c scope4 : E2_DataUtil.getScopeRecordsWithChildRecords(scope.id)){
                for(E2_Scope__c childScope : scope4.Child_Scopes__r){
                     childScopeIds.add(childScope.id);
                }
        }
        
      List<E2_Scope__c> scopeList = E2_DataUtil.getScopeRecordsWithChildForChildScopeIds(childScopeIds);
      System.assertEquals(scopeList[0].Efforts__r.size(), 3, '3 efforts should saved/updated');
      
      for(E2_AddNewScopeTemplateController.Effort eff: scope_wrap.efforts){
         eff.remove();    
      }         
      controller.saveScope();     
      scopeList = E2_DataUtil.getScopeAndChildrenOnScopeIdForEditScope(scope.id);
      System.assertEquals(scopeList[0].Efforts__r.size(), 0, 'all efforts should removed');
         
      controller.addNewScope();
      
      System.assertEquals(controller.childScopes.size(), 2, '1 more child scope should be added in list'); 
        
      for( E2_AddNewScopeTemplateController.Scope scope_wrap1 : controller.childScopes)  {
            scope_wrap1.remove();
      }
        
      controller.saveScope();     
      System.assertEquals([SELECT Id FROM E2_Scope__c WHERE Parent_Scope__c != null].size(), 0, 'both scopes should have been removed');
        

    //stop test
    Test.stopTest(); 
    } 
  }
  
  
  public static testmethod void testAddNewScope(){
    scopeGrp = [SELECT Id FROM E2_Scope_Group__c limit 1];
    psr = [SELECT Id FROM Presales_Request__c];
    
    E2_Scope__c scope1 = E2_Test_Utils.insertScope(false);
    scope1.Scope_Group__c = scopeGrp.Id;
    //create sys admin user
    User sysAdmin = E2_Test_Utils.insertUser(E2_Constants.PROFILE_SYS_ADMIN, true);
    
    System.runAs(sysAdmin){
    //start test
    Test.startTest();
      PageReference pageRef = Page.E2_AddNewScopeTemplate;
      Test.setCurrentPage(pageRef);
      ApexPages.currentPage().getParameters().put('scopegroup_id', scopeGrp.Id);
    
      ApexPages.StandardController stdController = new ApexPages.StandardController(scope1);
      E2_AddNewScopeTemplateController controller = new E2_AddNewScopeTemplateController(stdController);
    
      controller.pageAction();
      system.assert(controller.is_New == true);
      
      
      controller.addNewScope();      
      controller.saveScope();  

      ApexPages.currentPage().getParameters().remove('scopegroup_id');
      ApexPages.currentPage().getParameters().remove(E2_Constants.URL_KEY_IS_VIEW);
      
      
      E2_Scope__c pscope1 =  E2_Test_Utils.insertScope(false);
      pscope1.recordTypeId = recTypeId;
      pscope1.Scope_Group__c = scopeGrp.Id;  
      insert pscope1;
    
      
      E2_Scope__c childSC = E2_Test_Utils.insertScope(false);
      childSC.Scope_Group__c = scopeGrp.Id;
      childSC.Parent_Scope__c = pscope1.Id;
      childSC.recordTypeId = recTypeId;
      childSC.Complexity__c = 'Medium';
      insert childSC;  
      
      E2_Effort__c effort1 = E2_Test_Utils.insertEffort(true, childSC.Id);  
      
      ApexPages.currentPage().getParameters().put('scopegroup_id', scopeGrp.Id);
      ApexPages.currentPage().getParameters().put(E2_Constants.URL_KEY_IS_EDIT, 'true');
      stdController = new ApexPages.StandardController(pscope1);
      controller = new E2_AddNewScopeTemplateController(stdController); 
      controller.pageAction();
      system.assert(controller.is_Edit == true);      
      
      controller.childScopes.addAll(controller.childScopes);  
      System.assertEquals(controller.childScopes.size(), 2, '1 more child scope should be added in list'); 
      
      controller.saveScope();     
      System.assertEquals([SELECT Id FROM E2_Scope__c WHERE Parent_Scope__c =: pscope1.Id].size(), 1, 'both scopes should not have been removed');
      
      controller.childScopes.clear();  
      controller.pageAction();
      System.assertEquals(controller.childScopes.size(), 1, '1 child scope should be added in list'); 
      for( E2_AddNewScopeTemplateController.Scope scope_wrap : controller.childScopes)  {
         scope_wrap.efforts.addAll(scope_wrap.efforts);   
      } 
      controller.saveScope();  
      
    //stop test
    Test.stopTest();  
    }
  }
  
    static testmethod void processClipboardDataTest(){
        scopeGrp = [SELECT Id FROM E2_Scope_Group__c limit 1];
        
        E2_Scope__c scope1 = E2_Test_Utils.insertScope(false);
        scope1.Scope_Group__c = scopeGrp.Id;
        //create sys admin user
        User sysAdmin = E2_Test_Utils.insertUser(E2_Constants.PROFILE_SYS_ADMIN, true);
    
        System.runAs(sysAdmin){
            //start test
            Test.startTest();
              PageReference pageRef = Page.E2_AddNewScopeTemplate;
              Test.setCurrentPage(pageRef);
              ApexPages.currentPage().getParameters().put('scopegroup_id', scopeGrp.Id);
            
              ApexPages.StandardController stdController = new ApexPages.StandardController(scope1);
              E2_AddNewScopeTemplateController controller = new E2_AddNewScopeTemplateController(stdController);
            
              controller.pageAction();
              system.assert(controller.is_New == true);
              
              controller.clipboardData = '[ {"property1" : "", "property2" : "", "property3" : ""}]';
              controller.processClipboardData();
              
              System.assertEquals(controller.childScopes.size(), 1, 'should have 1 childscope added');
            
              Test.stopTest();
        }    
   }  
    
   //create test data
  @testSetup static void createTestData(){
    
    User solArchitect, accExecutive, delReviewer; 
    Account acc;
    Opportunity opp;
    E2_Scope__c scope1; 
      
    acc = E2_Test_Utils.insertAccount(true);
    opp = E2_Test_Utils.insertOpportunity(acc.Id, true);
    
    solArchitect = E2_Test_Utils.insertSysAdminUser(false);
    solArchitect.firstName = 'Test SA';
    insert solArchitect;
    
    accExecutive = E2_Test_Utils.insertSysAdminUser(false);
    accExecutive.firstName = 'Test AE';
    insert accExecutive;
    
    delReviewer = E2_Test_Utils.insertSysAdminUser(false);
    delReviewer.firstName = 'Test Reviewer';
    insert delReviewer;
    
    psr = E2_Test_Utils.insertPresalesReq(opp.Id, 'Demo', false);
    insert psr;
    
    scopeGrp = E2_Test_Utils.insertScopeGroup(true);
      
    scope1 =  E2_Test_Utils.insertScope(false);
    scope1.recordTypeId = recTypeId;
    scope1.Scope_Group__c = scopeGrp.id;  
    insert scope1;
    
      
    E2_Scope__c childSC = E2_Test_Utils.insertScope(false);
    childSC.Scope_Group__c = scopeGrp.Id;
    childSC.Parent_Scope__c = scope1.Id;
    childSC.recordTypeId = recTypeId;
    childSC.Complexity__c = 'Medium';
    insert childSC;  
      
    E2_Effort__c effort1 = E2_Test_Utils.insertEffort(true, childSC.Id);  
      
  }
}