src/objects/E2_Estimate_Milestone__c.object
<CustomObject>
    <description>This object is used to store all the milestone details associated with a presales estimate. Related to Estimator 2.0 App</description>
    <fields>
        <fullName>Estimate__c</fullName>
        <description>Association with presales estimate</description>
        <label>Estimate</label>
        <referenceTo>CMC_Presales_LOE__c</referenceTo>
        <relationshipLabel>Estimate Milestones</relationshipLabel>
        <relationshipName>Estimate_Milestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Milestone1__c</fullName>
        <description>Primary Milestone Name</description>
        <label>Milestone1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Milestone2__c</fullName>
        <description>Secondary Milestone Name</description>
        <label>Milestone2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <description>Order</description>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Estimate Milestone</label>
    <nameField>
        <displayFormat>EM-{0000000000}</displayFormat>
        <label>Estimate Milestone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Estimate Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/E2_Estimate_Milestone_Week__c.object
<CustomObject>
    <description>Junction object between Estimate Milestone and Estimate Week. Used in Estimator 2.0 App</description>
    <fields>
        <fullName>Estimate_Milestone__c</fullName>
        <label>Estimate Milestone</label>
        <referenceTo>E2_Estimate_Milestone__c</referenceTo>
        <relationshipLabel>Estimate Milestone Weeks</relationshipLabel>
        <relationshipName>Estimate_Milestone_Weeks</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Estimate_Week__c</fullName>
        <label>Estimate Week</label>
        <referenceTo>CMC_Estimate_Week__c</referenceTo>
        <relationshipLabel>Estimate Milestone Weeks</relationshipLabel>
        <relationshipName>Estimate_Milestone_Weeks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TextColorCode__c</fullName>
        <description>Stores the hex color code for the milestone descriptions</description>
        <label>TextColorCode</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Text__c</fullName>
        <description>Field stores the text value milestone description</description>
        <label>Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Estimate Milestone Week</label>
    <nameField>
        <displayFormat>EMW-{0000000000}</displayFormat>
        <label>Estimate Milestone Week Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Estimate Milestone Weeks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/E2_Milestone_Library__c.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Marks a template active or inactive .If active then it is available for use to the E2 users .</description>
        <inlineHelpText>If active ,then that template is available made available for use in E2 system else not .</inlineHelpText>
        <label>Is_Active?</label>
        <type>Checkbox</type>
    </fields>
    <label>Milestone Library</label>
    <nameField>
        <label>Milestone Library Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestone Library</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/E2_Timeline_Milestone__c.object
<CustomObject>
    <fields>
        <fullName>E2_Milestone_Library__c</fullName>
        <label>Milestone Library</label>
        <referenceTo>E2_Milestone_Library__c</referenceTo>
        <relationshipLabel>Timeline Milestones</relationshipLabel>
        <relationshipName>Timeline_Milestone</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is_Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Milestone1__c</fullName>
        <label>Milestone 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Milestone2__c</fullName>
        <label>Milestone 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Timeline Milestone</label>
    <nameField>
        <displayFormat>TM-{00000}</displayFormat>
        <label>Timeline_Milestone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timeline Milestone</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/E2_MilestoneDataUtil_WS.cls
/**=====================================================================
 * Appirio, Inc
 * Name: E2_MilestoneDataUtil_WS
 * Description: This is the utility class used by E2_MilestoneWSManager.cls
 * Created Date: Sept 12th, 2016
 * Created By: Arpita Bose(Appirio)
 * 
 * Date Modified       Modified By          Description
 * 
*  =====================================================================*/
public class E2_MilestoneDataUtil_WS {
    
    public static List<E2_Estimate_Milestone__c> getEstimateMilestones(String estimateId){
      //method to get all the estimate milestone records for an estimate    
      return [SELECT Id
                 FROM E2_Estimate_Milestone__c
                 WHERE Estimate__c = :estimateId];    
    }
    
    public static List<E2_Estimate_Milestone_Week__c> getEstimateMilestoneWeeks(Set<String> weekIds, Set<String> milestoneIds){
      //method to get milestone week for given set of milestoneIds and weekIds
      return [SELECT ID, Text__c, TextColorCode__c, Estimate_Milestone__c, Estimate_Week__c   
                FROM E2_Estimate_Milestone_Week__c
                WHERE Estimate_Week__c IN :weekIds
                AND Estimate_Milestone__c IN :milestoneIds];
    }
    
    public static List<E2_Estimate_Milestone__c> getMilestone(String estimateId, String milestoneId){
      //method to get all the estimate milestone records for an estimate    
      return [SELECT Id, Milestone1__c, Milestone2__c
                 FROM E2_Estimate_Milestone__c
                 WHERE Estimate__c = :estimateId 
                 AND Id = : milestoneId];    
    }
    
    public static List<E2_Estimate_Milestone_Week__c> getEstimateMilestoneWeeksforWeek(String weekId, String milestoneId){
      //method to get milestone week for given set of milestoneIds and weekIds
      return [SELECT ID, Text__c, TextColorCode__c, Estimate_Milestone__c, Estimate_Week__c   
                FROM E2_Estimate_Milestone_Week__c
                WHERE Estimate_Week__c = :weekId
                AND Estimate_Milestone__c = :milestoneId];
    }
    
    public static List<E2_Estimate_Milestone__c> getEstimateMilestoneAndAllWeeks(String estimateId){
      //method to get estimate milestone and all milestone week records for an estimate 
      return  [SELECT Id, Name, Milestone1__c, Milestone2__c, Order__c,  
                 (SELECT ID, Text__c, TextColorCode__c, Estimate_Week__c, Estimate_Milestone__c
                  FROM Estimate_Milestone_Weeks__r)  
                  FROM E2_Estimate_Milestone__c
                  WHERE Estimate__c = :estimateId
                  ORDER BY Order__c ASC];    
    }
    
    public static List<E2_Timeline_Milestone__c> getTimelineMilestones(String selectedLibrary){
      //method to get all active milestones related to selected milestone template library
      return  [SELECT Id, Name, Milestone1__c, Milestone2__c, Order__c  
                  FROM E2_Timeline_Milestone__c
                  WHERE E2_Milestone_Library__c = :selectedLibrary
                  AND Is_Active__c = true
                  ORDER BY Order__c ASC];    
    }
}