src/objects/E2_Favourite_Scope__c.object
<CustomObject>
    <description>Estimator 2.0: This is a junction object between User and E2_Scope__c to store details when a template is marked as favorite.</description>
    <fields>
        <fullName>Scope__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scope</label>
        <referenceTo>E2_Scope__c</referenceTo>
        <relationshipLabel>Favorite Scopes</relationshipLabel>
        <relationshipName>E2_Favourite_Scope</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unique_Scope_User_Id__c</fullName>
        <label>Unique Scope User Id</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>E2_Favourite_Scope</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Favorite Scope</label>
    <nameField>
        <displayFormat>E2FS-{0000}</displayFormat>
        <label>Favorite Scope Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Favorite Scopes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/E2_Scope__c.object
<CustomObject>
    <description>Estimator 2.0</description>
    <fields>
        <fullName>Is_Favourite__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When marked by the SA as favorite ,the SA can find the same in the &quot;My Scope&quot; section when adds a scope from template.</description>
        <inlineHelpText>When marked by the SA as favorite ,the SA can find the same in the &quot;My Scope&quot; section when adds a scope from template.</inlineHelpText>
        <label>Is Favourite</label>
        <type>Checkbox</type>
    </fields>
    <label>Scope</label>
    <nameField>
        <label>Scope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scope</pluralLabel>
    <recordTypes>
        <fullName>Scope</fullName>
        <active>true</active>
        <description>Default Scope Record type. Mostly all scope should use this record type</description>
        <label>Scope</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/E2_BatchCreateFavoriteScope.cls
/**=====================================================================
 * Appirio, Inc
 * Name: E2_BatchCreateFavoriteScope
 * Description: T-525253: Batch class to create E2_Favourite_Scope__c record for all the scopes 
                where Is_Favourite is true. This class will run only once to insert.
 * Created Date: August 9th, 2016
 * Created By: Arpita Bose (Appirio)
 * 
 * Date Modified      Modified By                  Description of the update
 *  
*  =====================================================================*/
global class E2_BatchCreateFavoriteScope implements  Database.Batchable<sObject>, Database.Stateful {
  
  // Start method
  global Database.QueryLocator start(Database.BatchableContext BC){
    //fetch all the scope records where Is_Favourite__c = true
    String query = '';
    query = 'SELECT Id, Name, Is_Favourite__c, CreatedById '+                       
                 'FROM E2_Scope__c '+ 
                 'WHERE Is_Favourite__c = true '+
                 ' ORDER By Name';
    return Database.getQueryLocator(query);
    
  }

  // Execute method
  global void execute(Database.BatchableContext BC, List<sObject> scope) {
    Set<Id> scopeIds = new Set<Id>();
    List<E2_Scope__c> scopeLst = new List<E2_Scope__c>();
    Map<String,E2_Favourite_Scope__c> favScopesMap = new Map<String,E2_Favourite_Scope__c>();
    List<E2_Favourite_Scope__c> favScopesToInsert = new List<E2_Favourite_Scope__c>();
    
    for(E2_Scope__c sc : (List<E2_Scope__c>)scope){
      scopeLst.add(sc);
      scopeIds.add(sc.Id);
    }
    
    // create a map of Favorite Scopes for all the above scopeIds( where Is_Favourite__c = true)
    for(E2_Favourite_Scope__c favSC : [SELECT Id, Scope__c, User__c, Unique_Scope_User_Id__c  
                                          FROM E2_Favourite_Scope__c 
                                          WHERE Scope__c IN:scopeIds] ){
      favScopesMap.put(favSC.Unique_Scope_User_Id__c, favSC);                                        
    }
    
    // insert Favorite Scopes if it's not exist in the above map for the scope list
    for(E2_Scope__c sc : scopeLst){
      String uniqueKey = sc.Id +'-'+ sc.CreatedById; 
      if(!favScopesMap.containsKey(uniqueKey)){
	      E2_Favourite_Scope__c newFavScope = new E2_Favourite_Scope__c();
	      newFavScope.Scope__c = sc.Id;
	      newFavScope.User__c = sc.CreatedById;
	      newFavScope.Unique_Scope_User_Id__c = uniqueKey;
	      favScopesToInsert.add(newFavScope);
      }  
    }
    //insert
    if(!favScopesToInsert.isEmpty()){
      insert favScopesToInsert;
    }
 
  }
  
  // Finish method
  global void finish(Database.BatchableContext BC) {
    
  }
}