src/objects/E2_Milestone_Library__c.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Marks a template active or inactive .If active then it is available for use to the E2 users .</description>
        <inlineHelpText>If active ,then that template is available made available for use in E2 system else not .</inlineHelpText>
        <label>Is_Active?</label>
        <type>Checkbox</type>
    </fields>
    <label>Milestone Library</label>
    <nameField>
        <label>Milestone Library Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestone Library</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/E2_Milestone_Week_Template_Junction__c.object
<CustomObject>
    <fields>
        <fullName>TextColorCode__c</fullName>
        <description>Stores the text colour of the milestone created in the template.</description>
        <inlineHelpText>Stores the text colour of the milestone created in the template.</inlineHelpText>
        <label>TextColorCode</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Text__c</fullName>
        <label>Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Timeline_Milestone__c</fullName>
        <label>Timeline Milestone</label>
        <referenceTo>E2_Timeline_Milestone__c</referenceTo>
        <relationshipLabel>Milestone Week Template Junction</relationshipLabel>
        <relationshipName>Milestone_Week_Template_Junction</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Week_Milestone_Template__c</fullName>
        <label>Week Milestone Template</label>
        <referenceTo>E2_Week_Milestone_Template__c</referenceTo>
        <relationshipLabel>Milestone Week Template Junction</relationshipLabel>
        <relationshipName>Milestone_Week_Template_Junction</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Milestone Week Template Junction</label>
    <nameField>
        <displayFormat>MWE-{0000}</displayFormat>
        <label>Milestone Week Template Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Milestone Week Template Junction</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/E2_Timeline_Milestone__c.object
<CustomObject>
    <fields>
        <fullName>E2_Milestone_Library__c</fullName>
        <label>Milestone Library</label>
        <referenceTo>E2_Milestone_Library__c</referenceTo>
        <relationshipLabel>Timeline Milestones</relationshipLabel>
        <relationshipName>Timeline_Milestone</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is_Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Milestone1__c</fullName>
        <label>Milestone 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Milestone2__c</fullName>
        <label>Milestone 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Timeline Milestone</label>
    <nameField>
        <displayFormat>TM-{00000}</displayFormat>
        <label>Timeline_Milestone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timeline Milestone</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/E2_Week_Milestone_Template__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <description>Store the date of the week created in the milestone template.</description>
        <inlineHelpText>Store the date of the week created in the milestone template.</inlineHelpText>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Milestone_Library__c</fullName>
        <description>Milestone library with which the week is associated .</description>
        <inlineHelpText>Milestone library with which the week is associated .</inlineHelpText>
        <label>Milestone Library</label>
        <referenceTo>E2_Milestone_Library__c</referenceTo>
        <relationshipLabel>Week Milestone Template</relationshipLabel>
        <relationshipName>Week_Milestone_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <description>Store the order number of the week created in the milestone.</description>
        <inlineHelpText>Store the order number of the week created in the milestone.</inlineHelpText>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Week Milestone Template</label>
    <nameField>
        <label>Week Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Week Milestone Template</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/E2_MilestoneTemplateDataUtil_WS.cls
/**=====================================================================
 * Appirio, Inc
 * Name: E2_MilestoneTemplateDataUtil_WS
 * Description: S-464465: This is the data utility class used by E2_MilestoneTemplateWSManager.cls
 * Created Date: Feb 5th, 2017
 * Created By: Rohit Sharma
 * 
 * Date Modified       Modified By          Description
 * 
*  =====================================================================*/
public class E2_MilestoneTemplateDataUtil_WS {
    
    public static List<E2_Timeline_Milestone__c> getTemplateMilestones(String templateId){
      //method to get all the Template milestone records for an Template    
      return [SELECT Id
                 FROM E2_Timeline_Milestone__c
                 WHERE E2_Milestone_Library__c = :templateId];    
    }
    
    public static List<E2_Milestone_Week_Template_Junction__c> getTemplateMilestoneWeeks(Set<String> weekIds, Set<String> milestoneIds){
      //method to get milestone week for given set of milestoneIds and weekIds
      return [SELECT ID, Text__c, TextColorCode__c, Timeline_Milestone__c, Week_Milestone_Template__c   
                FROM E2_Milestone_Week_Template_Junction__c
                WHERE Week_Milestone_Template__c IN :weekIds
                AND Timeline_Milestone__c IN :milestoneIds];
    }
    
    public static List<E2_Timeline_Milestone__c> getMilestone(String templateId, String milestoneId){
      //method to get all the Template milestone records for an Template    
      return [SELECT Id, Milestone1__c, Milestone2__c
                 FROM E2_Timeline_Milestone__c
                 WHERE E2_Milestone_Library__c = :templateId 
                 AND Id = : milestoneId];    
    }
    
    public static List<E2_Milestone_Week_Template_Junction__c> getTemplateMilestoneWeeksforWeek(String weekId, String milestoneId){
      //method to get milestone week for given set of milestoneIds and weekIds
      return [SELECT ID, Text__c, TextColorCode__c, Timeline_Milestone__c, Week_Milestone_Template__c   
                FROM E2_Milestone_Week_Template_Junction__c
                WHERE Week_Milestone_Template__c = :weekId
                AND Timeline_Milestone__c = :milestoneId];
    }
    
    public static List<E2_Timeline_Milestone__c> getTemplateMilestoneAndAllWeeks(String templateId){
      //method to get Template milestone and all milestone week records for an Template 
      return  [SELECT Id, Name, Milestone1__c, Milestone2__c, Order__c,  
                 (SELECT ID, Text__c, TextColorCode__c, Week_Milestone_Template__c, Timeline_Milestone__c
                  FROM Milestone_Week_Template_Junction__r)  
                  FROM E2_Timeline_Milestone__c
                  WHERE E2_Milestone_Library__c = :templateId
                  ORDER BY Order__c ASC];    
    }
    
    public static List<E2_Timeline_Milestone__c> getTimelineMilestones(String selectedLibrary){
      //method to get all active milestones related to selected milestone template library
      return  [SELECT Id, Name, Milestone1__c, Milestone2__c, Order__c  
                  FROM E2_Timeline_Milestone__c
                  WHERE E2_Milestone_Library__c = :selectedLibrary
                  AND Is_Active__c = true
                  ORDER BY Order__c ASC];    
    }
    
    //method to get E2_Week_Milestone_Template__c records for an templateId
    public static List<E2_Week_Milestone_Template__c> getTemplateWeekMilestoneRecords(String templateId){
        return [SELECT Id, Date__c, Name, Order__c, Milestone_Library__c
              FROM E2_Week_Milestone_Template__c                                                    
              WHERE Milestone_Library__c = :templateId
              ORDER BY Date__c ASC, Order__c ASC];
    }
}