src/objects/E2_Scope__c.object
<CustomObject>
    <description>Estimator 2.0</description>
    <fields>
        <fullName>Complexity__c</fullName>
        <description>Complexity (High, Medium, Low)</description>
        <globalPicklist>E2_Complexity</globalPicklist>
        <inlineHelpText>Complexity of this scope(High, Medium, Low)</inlineHelpText>
        <label>Complexity</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LOE_Hrs__c</fullName>
        <description>Calculated base field for estimates depending on complexity selected.</description>
        <inlineHelpText>Calculated base field for estimates depending on complexity selected.</inlineHelpText>
        <label>LOE Hrs</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scope_Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Contains the scopes relevant to the group.For eg: Sales cloud implementation with 100k records.</description>
        <inlineHelpText>Contains the scopes relevant to the group.For eg: Sales cloud implementation with 100k records.</inlineHelpText>
        <label>Scope Group</label>
        <referenceTo>E2_Scope_Group__c</referenceTo>
        <relationshipLabel>Scope</relationshipLabel>
        <relationshipName>Scopes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Scope</label>
    <nameField>
        <label>Scope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scope</pluralLabel>
    <recordTypes>
        <fullName>Scope</fullName>
        <active>true</active>
        <description>Default Scope Record type. Mostly all scope should use this record type</description>
        <label>Scope</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/E2_Scope_Group__c.object
<CustomObject>
    <description>Estimator 2.0</description>
    <label>Scope Library</label>
    <nameField>
        <label>E2 Scope Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scope Library</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/E2_ScopeWrapper.cls
/**=====================================================================
 * Appirio, Inc
 * Name: E2_ScopeWrapper
 * Description: Wrapper class of Scope used in ScopeTemplateSearch page
 * Created Date: Apr 8th, 2016
 * Created By: Rohit Sharma (Appirio)
 * 
 * Date Modified      Modified By                  Description of the update
    
*  =====================================================================*/
global class E2_ScopeWrapper implements Comparable {
    public Boolean isSelected {get; set;}
    public E2_Scope__c scope {get; set;}
    
    public enum SORT_BY {
        ByScopeName,ByComplexity,ByGroup,ByEfforts,ByLastView
    }
    
    public enum SORT_ORDER {
        ByDESC,ByASC
    }
    
    public static SORT_BY sortBy = SORT_BY.ByScopeName;
    public static SORT_ORDER sortOreder = SORT_ORDER.ByASC;


    //constructor    
    public E2_ScopeWrapper(){
      scope = new E2_Scope__c();
      isSelected = false;
    }
    
    public E2_ScopeWrapper(E2_Scope__c scope){
      this.scope = scope;
      isSelected = false;
    }
    
    global Integer compareTo(Object objToCompare) {
        if(sortBy == SORT_BY.ByComplexity){
            if(sortOreder==SORT_ORDER.ByASC) 
                return scope.Complexity__c.compareTo(((E2_ScopeWrapper)objToCompare).scope.Complexity__c);
            else
                return ((E2_ScopeWrapper)objToCompare).scope.Complexity__c.compareTo(scope.Complexity__c); 
        }else if(sortBy == SORT_BY.ByGroup){
            if(scope.Scope_Group__c==null) {
                return -1;
            }else if(((E2_ScopeWrapper)objToCompare).scope.Scope_Group__c==null) {
                return 1;
            }
            if(sortOreder==SORT_ORDER.ByASC) 
                return scope.Scope_Group__r.Name.compareTo(((E2_ScopeWrapper)objToCompare).scope.Scope_Group__r.Name);
            else
                return ((E2_ScopeWrapper)objToCompare).scope.Scope_Group__r.Name.compareTo(scope.Scope_Group__r.Name);
        }else if(sortBy == SORT_BY.ByEfforts){
            if(sortOreder==SORT_ORDER.ByASC) 
                return Integer.valueOf(scope.LOE_Hrs__c - ((E2_ScopeWrapper)objToCompare).scope.LOE_Hrs__c);
            else
                return Integer.valueOf(((E2_ScopeWrapper)objToCompare).scope.LOE_Hrs__c - scope.LOE_Hrs__c);
        }else if(sortBy == SORT_BY.ByLastView) {
            return 0;//scope.LastViewedDate==null ? -1 : ((E2_ScopeWrapper)objToCompare).scope.LastViewedDate==null ? 0 : Integer.valueOf((scope.LastViewedDate.getTime() / 1000) - (((E2_ScopeWrapper)objToCompare).scope.LastViewedDate.getTime() /1000));
        }else {
           if(sortOreder==SORT_ORDER.ByASC) 
                return scope.Name.compareTo(((E2_ScopeWrapper)objToCompare).scope.Name);
            else
                return ((E2_ScopeWrapper)objToCompare).scope.Name.compareTo(scope.Name); 
        }
    }
    
  }