src/objects/E2_Scope__c.object
<CustomObject>
    <description>Estimator 2.0</description>
    <fields>
        <fullName>Parent_Scope__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent scope of this scope.</description>
        <inlineHelpText>(Optional) - Parent scope of this scope.</inlineHelpText>
        <label>Parent Scope</label>
        <referenceTo>E2_Scope__c</referenceTo>
        <relationshipName>Child_Scopes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ultimate_Parent_Id__c</fullName>
        <formula>IF( NOT( ISBLANK( Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__c )),Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__c ,
IF( NOT(ISBLANK(Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__c)), Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__c,
IF(NOT(ISBLANK(Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__c)),
Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__c,
IF(NOT(ISBLANK(Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__c)),
Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__c,
IF(NOT(ISBLANK(Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__c)),Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__c,
IF(NOT(ISBLANK(Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__c)),
Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__c,
IF(NOT(ISBLANK(Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__c)), Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__c,
IF(NOT(ISBLANK(Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__c)), Parent_Scope__r.Parent_Scope__r.Parent_Scope__r.Parent_Scope__c,
IF(NOT(ISBLANK(Parent_Scope__r.Parent_Scope__r.Parent_Scope__c)), Parent_Scope__r.Parent_Scope__r.Parent_Scope__c,
IF(NOT(ISBLANK(Parent_Scope__r.Parent_Scope__c)),Parent_Scope__r.Parent_Scope__c,
IF(NOT(ISBLANK(Parent_Scope__c)),Parent_Scope__c, NULL)))))))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This ID is used by Scope LOE Hrs calculation for all its child scopes</inlineHelpText>
        <label>Ultimate Parent Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ultimate_Parent_Scope__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the ultimate (topmost )scope that the current scope is pointing to.</description>
        <inlineHelpText>This is the ultimate i.e. the topmost scope that the current scope is pointing to.</inlineHelpText>
        <label>Ultimate Parent Scope</label>
        <referenceTo>E2_Scope__c</referenceTo>
        <relationshipName>E2_Scopes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Scope</label>
    <nameField>
        <label>Scope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scope</pluralLabel>
    <recordTypes>
        <fullName>Scope</fullName>
        <active>true</active>
        <description>Default Scope Record type. Mostly all scope should use this record type</description>
        <label>Scope</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/E2_BatchUpdateUltimateParentScope.cls
/**=====================================================================
 * Appirio, Inc
 * Name: E2_BatchUpdateUltimateParentScope
 * Description: Batch class to update Ultimate Parent on Scope. This class will run once
                and update Ultimate Parent on all the existing Scope records where Parent is not null
 * Created Date: August 9th, 2016
 * Created By: Arpita Bose (Appirio)
 * 
 * Date Modified      Modified By                  Description of the update
 *  
*  =====================================================================*/
global class E2_BatchUpdateUltimateParentScope implements  Database.Batchable<sObject>, Database.Stateful {

  // Start method
  global Database.QueryLocator start(Database.BatchableContext BC){
    //query all scopes where Parent Scope is not null
    String query = '';
    query = 'SELECT Id, Ultimate_Parent_Id__c, Ultimate_Parent_Scope__c '+                         
            'FROM E2_Scope__c '+ 
            'WHERE Parent_Scope__c != null';
   
    return Database.getQueryLocator(query);
  }

  // Execute method
  global void execute(Database.BatchableContext BC, List<sObject> scope) {
    List<E2_Scope__c> scopeLstToUpdate = new List<E2_Scope__c>();
    //assign Ultimate Parent Id if it's not null, to ultimate Parent Scope
    for(E2_Scope__c sc : (List<E2_Scope__c>)scope){
      if(!string.isBlank(sc.Ultimate_Parent_Id__c)) {
          sc.Ultimate_Parent_Scope__c = sc.Ultimate_Parent_Id__c;
          scopeLstToUpdate.add(sc);
      }
    }
     //update scopes
     if(!scopeLstToUpdate.isEmpty()){
         update scopeLstToUpdate;
     }
  }

  // Finish method
  global void finish(Database.BatchableContext BC) {
    
  }
}